// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArrowDown: ImageVector by lazy {
    ImageVector.Builder(
        name = "ArrowDown",
        defaultWidth = 24f.dp,
        defaultHeight = 24f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        // color-agnostic -- tint at the call site
        path(fill = SolidColor(Color.Black)) {
            moveTo(11f, 3f)
            lineTo(13f, 3f)
            lineTo(13f, 13f)
            lineTo(11f, 13f)
            close()
            moveTo(4f, 12f)
            lineTo(20f, 12f)
            lineTo(12f, 21f)
            close()
        }
    }.build()
}
