// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Check: ImageVector by lazy {
    ImageVector.Builder(
        name = "Check",
        defaultWidth = 24f.dp,
        defaultHeight = 24f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        // color-agnostic -- tint at the call site
        path(fill = SolidColor(Color.Black)) {
            moveTo(2f, 13f)
            lineTo(9f, 20f)
            lineTo(22f, 4f)
            lineTo(20f, 2f)
            lineTo(9f, 15f)
            lineTo(4f, 10f)
            close()
        }
    }.build()
}
