// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Menu: ImageVector by lazy {
    ImageVector.Builder(
        name = "Menu",
        defaultWidth = 24f.dp,
        defaultHeight = 24f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        // color-agnostic -- tint at the call site
        path(fill = SolidColor(Color.Black)) {
            moveTo(3f, 5f)
            lineTo(21f, 5f)
            lineTo(21f, 7f)
            lineTo(3f, 7f)
            close()
            moveTo(3f, 11f)
            lineTo(21f, 11f)
            lineTo(21f, 13f)
            lineTo(3f, 13f)
            close()
            moveTo(3f, 17f)
            lineTo(21f, 17f)
            lineTo(21f, 19f)
            lineTo(3f, 19f)
            close()
        }
    }.build()
}
