// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MoreHorizontal: ImageVector by lazy {
    ImageVector.Builder(
        name = "MoreHorizontal",
        defaultWidth = 24f.dp,
        defaultHeight = 24f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        // color-agnostic -- tint at the call site
        path(fill = SolidColor(Color.Black)) {
            moveTo(5f, 10.2f)
            curveTo(5.99f, 10.2f, 6.8f, 10.99f, 6.8f, 12f)
            curveTo(6.8f, 13.01f, 5.99f, 13.8f, 5f, 13.8f)
            curveTo(4.01f, 13.8f, 3.2f, 13.01f, 3.2f, 12f)
            curveTo(3.2f, 10.99f, 4.01f, 10.2f, 5f, 10.2f)
            close()
            moveTo(12f, 10.2f)
            curveTo(12.99f, 10.2f, 13.8f, 10.99f, 13.8f, 12f)
            curveTo(13.8f, 13.01f, 12.99f, 13.8f, 12f, 13.8f)
            curveTo(11.01f, 13.8f, 10.2f, 13.01f, 10.2f, 12f)
            curveTo(10.2f, 10.99f, 11.01f, 10.2f, 12f, 10.2f)
            close()
            moveTo(19f, 10.2f)
            curveTo(19.99f, 10.2f, 20.8f, 10.99f, 20.8f, 12f)
            curveTo(20.8f, 13.01f, 19.99f, 13.8f, 19f, 13.8f)
            curveTo(18.01f, 13.8f, 17.2f, 13.01f, 17.2f, 12f)
            curveTo(17.2f, 10.99f, 18.01f, 10.2f, 19f, 10.2f)
            close()
        }
    }.build()
}
