// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val X: ImageVector by lazy {
    ImageVector.Builder(
        name = "X",
        defaultWidth = 24f.dp,
        defaultHeight = 24f.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        // color-agnostic -- tint at the call site
        path(fill = SolidColor(Color.Black)) {
            moveTo(5f, 7f)
            lineTo(7f, 5f)
            lineTo(19f, 17f)
            lineTo(17f, 19f)
            close()
            moveTo(17f, 5f)
            lineTo(19f, 7f)
            lineTo(7f, 19f)
            lineTo(5f, 17f)
            close()
        }
    }.build()
}
