#!/usr/bin/env python3
"""
KMM Layout System — slot-grid scaffold generator.

Reads the slot-grid frontmatter from a docs/layout-system/<screen>.md wireframe file and
emits a <Screen>Layout.kt shell: one `when (windowSizeClass.widthSizeClass)` branch per
breakpoint, each slot exposed as a @Composable () -> Unit parameter. The agent fills slot
CONTENT only — it never writes Row/weight/width structure or guesses proportions.

The wireframe frontmatter is the single source of truth. To change the layout, edit the
frontmatter and re-run this script — never hand-edit the generated structure.

Usage:
  python3 generate_slot_scaffold.py docs/layout-system/inbox.md \
    --group-id com.example.app --output composeApp/src/commonMain/kotlin/.../home/
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

GENERATED_HEADER = "// GENERATED by generate_slot_scaffold from the layout-system contract — edit the wireframe frontmatter and re-run instead."

_FM_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)
_LIST_RE = re.compile(r"\[([^\]]*)\]")
_MAP_RE = re.compile(r"\{([^}]*)\}")
ALLOWED_WEIGHTS = {"0.5f", "1f", "1.5f", "2f", "2.5f", "3f", "4f", "fixed", "overlay"}
BREAKPOINTS = ("compact", "medium", "expanded")


def parse_frontmatter(text: str) -> dict:
    m = _FM_RE.match(text)
    if not m:
        raise ValueError("no frontmatter block — regenerate the wireframe with create_wireframe.py")
    fm: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        fm[key.strip()] = value.strip()
    return fm


def _parse_list(raw: str) -> list[str]:
    m = _LIST_RE.search(raw)
    if not m:
        raise ValueError(f"expected a [list], got: {raw}")
    return [p.strip() for p in m.group(1).split(",") if p.strip()]


def _parse_map(raw: str) -> dict[str, str]:
    m = _MAP_RE.search(raw)
    if not m:
        raise ValueError(f"expected a {{map}}, got: {raw}")
    out: dict[str, str] = {}
    # Split on commas that are not inside brackets
    depth = 0
    part = ""
    parts: list[str] = []
    for ch in m.group(1):
        if ch == "[":
            depth += 1
        elif ch == "]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(part)
            part = ""
        else:
            part += ch
    if part.strip():
        parts.append(part)
    for p in parts:
        k, _, v = p.partition(":")
        out[k.strip()] = v.strip()
    return out


def load_contract(wireframe: Path) -> dict:
    fm = parse_frontmatter(wireframe.read_text(encoding="utf-8"))
    for req in ("screen", "slots", "grid", "weights"):
        if req not in fm:
            raise ValueError(f"frontmatter missing '{req}' — regenerate with create_wireframe.py")
    slots = _parse_list(fm["slots"])
    grid_raw = _parse_map(fm["grid"])
    grid = {bp: _parse_list(v) for bp, v in grid_raw.items()}
    weights = _parse_map(fm["weights"])

    # Validate: every breakpoint present; every grid slot declared; weights from closed set
    for bp in BREAKPOINTS:
        if bp not in grid:
            raise ValueError(f"grid missing breakpoint '{bp}' — all three are required")
        for s in grid[bp]:
            if s not in slots:
                raise ValueError(f"grid references undeclared slot '{s}'")
    for slot, w in weights.items():
        if w not in ALLOWED_WEIGHTS:
            raise ValueError(
                f"weight '{w}' for slot '{slot}' is not in the closed set "
                f"{sorted(ALLOWED_WEIGHTS)} — arbitrary proportions are forbidden"
            )
    return {"screen": fm["screen"], "slots": slots, "grid": grid, "weights": weights}


def pascal(name: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[^a-zA-Z0-9]+", name) if p)


def _slot_call(slot: str, weight: str) -> str:
    if weight == "fixed":
        return f"Box {{ {slot}() }}                       // fixed-width chrome — size inside the slot"
    if weight == "overlay":
        return f"{slot}()                                 // overlay — renders above, no row space"
    return f"Box(Modifier.weight({weight})) {{ {slot}() }}"


def generate_kotlin(contract: dict, group_id: str) -> str:
    screen = pascal(contract["screen"])
    slots = contract["slots"]
    grid = contract["grid"]
    weights = contract["weights"]

    params = "\n".join(f"    {s}: @Composable () -> Unit," for s in slots)

    branches = []
    for bp in BREAKPOINTS:
        wsc = bp.capitalize()
        inline = grid[bp]
        row_slots = [s for s in inline if weights.get(s) != "overlay"]
        overlay_slots = [s for s in inline if weights.get(s) == "overlay"]
        calls = "\n".join(f"                {_slot_call(s, weights.get(s, '1f'))}" for s in row_slots)
        overlay = "".join(f"\n            {s}()" for s in overlay_slots)
        branches.append(
            f"        WindowWidthSizeClass.{wsc} -> {{\n"
            f"            Row(Modifier.fillMaxSize()) {{\n{calls}\n            }}{overlay}\n"
            f"        }}"
        )
    when_block = "\n".join(branches)

    return f"""\
{GENERATED_HEADER}
package {group_id}.feature.{contract["screen"].replace("-", "")}.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.windowsizeclass.WindowSizeClass
import androidx.compose.material3.windowsizeclass.WindowWidthSizeClass
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

/**
 * Slot-grid layout for `{contract["screen"]}` — structure comes from the layout-system
 * contract (docs/layout-system/{contract["screen"]}.md). Fill the slots; never edit the
 * Row/weight structure here.
 */
@Composable
fun {screen}Layout(
    windowSizeClass: WindowSizeClass,
{params}
) {{
    when (windowSizeClass.widthSizeClass) {{
{when_block}
        else -> {{
            Row(Modifier.fillMaxSize()) {{
                {_slot_call(grid["compact"][0], weights.get(grid["compact"][0], "1f"))}
            }}
        }}
    }}
}}
"""


def main() -> int:
    p = argparse.ArgumentParser(description="Generate a slot-grid layout shell from a wireframe contract.")
    p.add_argument("wireframe", type=Path, help="docs/layout-system/<screen>.md with slot frontmatter")
    p.add_argument("--group-id", default="com.example.app")
    p.add_argument("--output", type=Path, default=Path("."), help="Directory for <Screen>Layout.kt")
    args = p.parse_args()

    if not args.wireframe.exists():
        print(f"error: {args.wireframe} not found", file=sys.stderr)
        return 2

    contract = load_contract(args.wireframe)
    kotlin = generate_kotlin(contract, args.group_id)

    args.output.mkdir(parents=True, exist_ok=True)
    out = args.output / f"{pascal(contract['screen'])}Layout.kt"
    out.write_text(kotlin, encoding="utf-8")
    print(f"✅  {out}")
    print(f"    slots: {', '.join(contract['slots'])}  |  breakpoints: compact/medium/expanded")
    print("    Fill the slot lambdas — the Row/weight structure is contract-owned; to change it,")
    print("    edit the wireframe frontmatter and re-run this script.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
