// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Astonished: ImageVector by lazy {
    ImageVector.Builder(
        name = "Astonished",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFCC4D))) {
            moveTo(36f, 18f)
            curveTo(36f, 27.94f, 27.94f, 36f, 18f, 36f)
            curveTo(8.06f, 36f, 0f, 27.94f, 0f, 18f)
            curveTo(0f, 8.06f, 8.06f, 0f, 18f, 0f)
            curveTo(27.94f, 0f, 36f, 8.06f, 36f, 18f)
        }
    }.build()
}
