// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Chair: ImageVector by lazy {
    ImageVector.Builder(
        name = "Chair",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFA4523A))) {
            moveTo(12f, 20f)
            curveTo(10.9f, 20f, 10f, 20.9f, 10f, 22f)
            lineTo(10f, 32f)
            curveTo(10f, 33.1f, 10.9f, 34f, 12f, 34f)
            curveTo(13.1f, 34f, 14f, 33.1f, 14f, 32f)
            lineTo(14f, 22f)
            curveTo(14f, 20.9f, 13.1f, 20f, 12f, 20f)
            close()
            moveTo(30f, 20f)
            curveTo(28.9f, 20f, 28f, 20.9f, 28f, 22f)
            lineTo(28f, 32f)
            curveTo(28f, 33.1f, 28.9f, 34f, 30f, 34f)
            curveTo(31.1f, 34f, 32f, 33.1f, 32f, 32f)
            lineTo(32f, 22f)
            curveTo(32f, 20.9f, 31.1f, 20f, 30f, 20f)
            close()
        }
        path(fill = SolidColor(Color(0xFFC1694F))) {
            moveTo(13f, 2f)
            lineTo(29f, 2f)
            lineTo(29f, 10f)
            lineTo(13f, 10f)
            close()
        }
        path(fill = SolidColor(Color(0xFFC1694F))) {
            moveTo(16f, 9f)
            lineTo(18f, 9f)
            lineTo(18f, 22f)
            lineTo(16f, 22f)
            close()
            moveTo(20f, 9f)
            lineTo(22f, 9f)
            lineTo(22f, 22f)
            lineTo(20f, 22f)
            close()
            moveTo(24f, 9f)
            lineTo(26f, 9f)
            lineTo(26f, 22f)
            lineTo(24f, 22f)
            close()
            moveTo(7f, 23f)
            curveTo(5.9f, 23f, 5f, 23.9f, 5f, 25f)
            lineTo(5f, 34f)
            curveTo(5f, 35.1f, 5.9f, 36f, 7f, 36f)
            curveTo(8.1f, 36f, 9f, 35.1f, 9f, 34f)
            lineTo(9f, 25f)
            curveTo(9f, 23.9f, 8.1f, 23f, 7f, 23f)
            close()
        }
        path(fill = SolidColor(Color(0xFFC1694F))) {
            moveTo(25f, 21f)
            curveTo(23.9f, 21f, 23f, 21.9f, 23f, 23f)
            lineTo(23f, 34f)
            curveTo(23f, 35.1f, 23.9f, 36f, 25f, 36f)
            curveTo(26.1f, 36f, 27f, 35.1f, 27f, 34f)
            lineTo(27f, 23f)
            curveTo(27f, 21.9f, 26.1f, 21f, 25f, 21f)
            close()
            moveTo(12f, 0f)
            curveTo(10.9f, 0f, 10f, 0.9f, 10f, 2f)
            lineTo(10f, 22f)
            lineTo(14f, 22f)
            lineTo(14f, 2f)
            curveTo(14f, 0.9f, 13.1f, 0f, 12f, 0f)
            close()
            moveTo(30f, 0f)
            curveTo(28.9f, 0f, 28f, 0.9f, 28f, 2f)
            lineTo(28f, 22f)
            lineTo(32f, 22f)
            lineTo(32f, 2f)
            curveTo(32f, 0.9f, 31.1f, 0f, 30f, 0f)
            close()
        }
        path(fill = SolidColor(Color(0xFFA4523A))) {
            moveTo(14f, 2f)
            lineTo(15f, 2f)
            lineTo(15f, 10f)
            lineTo(14f, 10f)
            close()
            moveTo(28f, 10f)
            lineTo(27f, 10f)
            lineTo(27f, 2f)
            lineTo(28f, 2f)
            close()
        }
        path(fill = SolidColor(Color(0xFFD99E82))) {
            moveTo(30.77f, 20f)
            lineTo(10.34f, 20f)
            curveTo(10.12f, 20f, 9.9f, 20.06f, 9.71f, 20.18f)
            lineTo(3.75f, 23.22f)
            curveTo(3.75f, 23.22f, 26.48f, 25.63f, 28.48f, 25.63f)
            lineTo(31.51f, 23.37f)
            curveTo(31.82f, 23.14f, 32f, 22.77f, 32f, 22.38f)
            lineTo(32f, 21.23f)
            curveTo(32f, 20.55f, 31.45f, 20f, 30.77f, 20f)
            close()
        }
        path(fill = SolidColor(Color(0xFFA4523A))) {
            moveTo(16f, 10f)
            lineTo(18f, 10f)
            lineTo(18f, 11f)
            lineTo(16f, 11f)
            close()
            moveTo(5f, 26f)
            lineTo(9f, 26f)
            lineTo(9f, 27f)
            lineTo(5f, 27f)
            close()
            moveTo(23f, 26f)
            lineTo(27f, 26f)
            lineTo(27f, 27f)
            lineTo(23f, 27f)
            close()
            moveTo(20f, 10f)
            lineTo(22f, 10f)
            lineTo(22f, 11f)
            lineTo(20f, 11f)
            close()
            moveTo(24f, 10f)
            lineTo(26f, 10f)
            lineTo(26f, 11f)
            lineTo(24f, 11f)
            close()
        }
        path(fill = SolidColor(Color(0xFFC1694F))) {
            moveTo(27.44f, 26f)
            lineTo(4.56f, 26f)
            curveTo(3.7f, 26f, 3f, 25.33f, 3f, 24.5f)
            curveTo(3f, 23.67f, 3.7f, 23f, 4.56f, 23f)
            lineTo(27.44f, 23f)
            curveTo(28.3f, 23f, 29f, 23.67f, 29f, 24.5f)
            curveTo(29f, 25.33f, 28.3f, 26f, 27.44f, 26f)
            close()
        }
    }.build()
}
