// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CheckMark: ImageVector by lazy {
    ImageVector.Builder(
        name = "CheckMark",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFF77B255))) {
            moveTo(36f, 32f)
            curveTo(36f, 34.21f, 34.21f, 36f, 32f, 36f)
            lineTo(4f, 36f)
            curveTo(1.79f, 36f, 0f, 34.21f, 0f, 32f)
            lineTo(0f, 4f)
            curveTo(0f, 1.79f, 1.79f, 0f, 4f, 0f)
            lineTo(32f, 0f)
            curveTo(34.21f, 0f, 36f, 1.79f, 36f, 4f)
            lineTo(36f, 32f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF))) {
            moveTo(29.28f, 6.36f)
            curveTo(28.12f, 5.61f, 26.58f, 5.94f, 25.82f, 7.1f)
            lineTo(14.94f, 23.88f)
            lineTo(9.91f, 19.23f)
            curveTo(8.89f, 18.29f, 7.31f, 18.35f, 6.37f, 19.36f)
            curveTo(5.44f, 20.38f, 5.5f, 21.96f, 6.51f, 22.9f)
            lineTo(13.72f, 29.56f)
            curveTo(14.2f, 30.01f, 14.81f, 30.23f, 15.42f, 30.23f)
            curveTo(16.09f, 30.23f, 16.95f, 29.95f, 17.52f, 29.09f)
            curveTo(17.85f, 28.58f, 30.02f, 9.82f, 30.02f, 9.82f)
            curveTo(30.77f, 8.66f, 30.44f, 7.11f, 29.28f, 6.36f)
            close()
        }
    }.build()
}
