// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CrossMark: ImageVector by lazy {
    ImageVector.Builder(
        name = "CrossMark",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFDD2E44))) {
            moveTo(21.53f, 18f)
            lineTo(33.77f, 5.77f)
            curveTo(34.74f, 4.79f, 34.74f, 3.21f, 33.77f, 2.23f)
            curveTo(32.79f, 1.26f, 31.21f, 1.26f, 30.23f, 2.23f)
            lineTo(18f, 14.47f)
            lineTo(5.76f, 2.23f)
            curveTo(4.79f, 1.26f, 3.2f, 1.26f, 2.23f, 2.23f)
            curveTo(1.25f, 3.21f, 1.25f, 4.79f, 2.23f, 5.77f)
            lineTo(14.46f, 18f)
            lineTo(2.2f, 30.27f)
            curveTo(1.22f, 31.24f, 1.22f, 32.82f, 2.2f, 33.8f)
            curveTo(2.69f, 34.29f, 3.33f, 34.53f, 3.97f, 34.53f)
            curveTo(4.61f, 34.53f, 5.25f, 34.29f, 5.74f, 33.8f)
            lineTo(18f, 21.54f)
            lineTo(30.23f, 33.77f)
            curveTo(30.72f, 34.26f, 31.36f, 34.5f, 32f, 34.5f)
            curveTo(32.64f, 34.5f, 33.28f, 34.26f, 33.77f, 33.77f)
            curveTo(34.75f, 32.79f, 34.75f, 31.21f, 33.77f, 30.24f)
            lineTo(21.53f, 18f)
            close()
        }
    }.build()
}
