// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Cry: ImageVector by lazy {
    ImageVector.Builder(
        name = "Cry",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFCC4D))) {
            moveTo(36f, 18f)
            curveTo(36f, 27.94f, 27.94f, 36f, 18f, 36f)
            curveTo(8.06f, 36f, 0f, 27.94f, 0f, 18f)
            curveTo(0f, 8.06f, 8.06f, 0f, 18f, 0f)
            curveTo(27.94f, 0f, 36f, 8.06f, 36f, 18f)
        }
        path(fill = SolidColor(Color(0xFF664500))) {
            moveTo(6f, 13.5f)
            curveTo(5.79f, 13.5f, 5.58f, 13.44f, 5.4f, 13.3f)
            curveTo(4.96f, 12.97f, 4.87f, 12.34f, 5.2f, 11.9f)
            curveTo(8.46f, 7.55f, 12.82f, 7.5f, 13f, 7.5f)
            curveTo(13.55f, 7.5f, 14f, 7.95f, 14f, 8.5f)
            curveTo(14f, 9.05f, 13.55f, 9.5f, 13f, 9.5f)
            curveTo(12.85f, 9.5f, 9.44f, 9.59f, 6.8f, 13.1f)
            curveTo(6.6f, 13.36f, 6.3f, 13.5f, 6f, 13.5f)
            close()
            moveTo(30f, 13.5f)
            curveTo(29.7f, 13.5f, 29.4f, 13.36f, 29.2f, 13.1f)
            curveTo(26.56f, 9.58f, 23.14f, 9.5f, 22.99f, 9.5f)
            curveTo(22.44f, 9.49f, 22f, 9.04f, 22f, 8.5f)
            curveTo(22.01f, 7.94f, 22.45f, 7.5f, 23f, 7.5f)
            curveTo(23.18f, 7.5f, 27.54f, 7.55f, 30.8f, 11.9f)
            curveTo(31.13f, 12.34f, 31.04f, 12.97f, 30.6f, 13.3f)
            curveTo(30.42f, 13.44f, 30.21f, 13.5f, 30f, 13.5f)
            close()
            moveTo(23.48f, 28.38f)
            curveTo(23.47f, 28.34f, 22.34f, 24f, 18f, 24f)
            curveTo(13.66f, 24f, 12.53f, 28.34f, 12.52f, 28.38f)
            curveTo(12.46f, 28.59f, 12.56f, 28.81f, 12.75f, 28.92f)
            curveTo(12.94f, 29.03f, 13.18f, 29.01f, 13.34f, 28.86f)
            curveTo(13.35f, 28.86f, 14.36f, 28f, 18f, 28f)
            curveTo(21.59f, 28f, 22.62f, 28.83f, 22.66f, 28.86f)
            curveTo(22.75f, 28.95f, 22.88f, 29f, 23f, 29f)
            curveTo(23.08f, 29f, 23.17f, 28.98f, 23.25f, 28.94f)
            curveTo(23.44f, 28.82f, 23.54f, 28.6f, 23.48f, 28.38f)
            close()
        }
        path(fill = SolidColor(Color(0xFF5DADEC))) {
            moveTo(16f, 31f)
            curveTo(16f, 33.76f, 13.76f, 36f, 11f, 36f)
            curveTo(8.24f, 36f, 6f, 33.76f, 6f, 31f)
            curveTo(6f, 28.24f, 10f, 21f, 11f, 21f)
            curveTo(12f, 21f, 16f, 28.24f, 16f, 31f)
            close()
        }
    }.build()
}
