// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Fire: ImageVector by lazy {
    ImageVector.Builder(
        name = "Fire",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFF4900C))) {
            moveTo(35f, 19f)
            curveTo(35f, 16.94f, 34.63f, 14.96f, 33.96f, 13.13f)
            curveTo(33.5f, 18.52f, 30.63f, 21.29f, 27.62f, 20f)
            curveTo(24.81f, 18.79f, 26.71f, 14.08f, 26.85f, 11.84f)
            curveTo(27.08f, 8.03f, 26.84f, 3.67f, 19.92f, 0.04f)
            curveTo(22.79f, 5.54f, 20.25f, 8.96f, 17.58f, 9.17f)
            curveTo(14.63f, 9.4f, 11.92f, 6.62f, 12.92f, 2.12f)
            curveTo(9.68f, 4.51f, 9.58f, 8.53f, 10.58f, 11.12f)
            curveTo(11.63f, 13.83f, 10.54f, 16.08f, 8f, 16.33f)
            curveTo(5.16f, 16.61f, 3.58f, 13.29f, 5.04f, 8f)
            curveTo(2.52f, 10.96f, 1f, 14.8f, 1f, 19f)
            curveTo(1f, 28.39f, 8.61f, 36f, 18f, 36f)
            curveTo(27.39f, 36f, 35f, 28.39f, 35f, 19f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFCC4D))) {
            moveTo(28.39f, 24f)
            curveTo(28.54f, 27.08f, 25.83f, 28.29f, 24.38f, 27.71f)
            curveTo(22.27f, 26.86f, 22.83f, 25.42f, 22.29f, 22.42f)
            curveTo(21.75f, 19.42f, 19.67f, 17.33f, 16.58f, 16.42f)
            curveTo(18.83f, 22.75f, 15.34f, 25.08f, 13.5f, 25.5f)
            curveTo(11.63f, 25.93f, 9.75f, 25.5f, 9.54f, 21.49f)
            curveTo(7.35f, 23.67f, 6f, 26.68f, 6f, 30f)
            curveTo(6f, 30.37f, 6.02f, 30.73f, 6.05f, 31.09f)
            curveTo(9.12f, 34.12f, 13.34f, 36f, 18f, 36f)
            curveTo(22.66f, 36f, 26.88f, 34.12f, 29.95f, 31.09f)
            curveTo(29.98f, 30.73f, 30f, 30.37f, 30f, 30f)
            curveTo(30f, 27.81f, 29.42f, 25.76f, 28.39f, 24f)
            close()
        }
    }.build()
}
