// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FramedPicture: ImageVector by lazy {
    ImageVector.Builder(
        name = "FramedPicture",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFD79E84))) {
            moveTo(35f, 30f)
            curveTo(35f, 31.1f, 34.1f, 32f, 33f, 32f)
            lineTo(3f, 32f)
            curveTo(1.9f, 32f, 1f, 31.1f, 1f, 30f)
            lineTo(1f, 6f)
            curveTo(1f, 4.9f, 1.9f, 4f, 3f, 4f)
            lineTo(33f, 4f)
            curveTo(34.1f, 4f, 35f, 4.9f, 35f, 6f)
            lineTo(35f, 30f)
            close()
        }
        path(fill = SolidColor(Color(0xFFBF6952))) {
            moveTo(33f, 4f)
            lineTo(3f, 4f)
            curveTo(1.9f, 4f, 1f, 4.9f, 1f, 6f)
            lineTo(1f, 30f)
            curveTo(1f, 30.39f, 1.12f, 30.75f, 1.31f, 31.05f)
            lineTo(34.64f, 4.86f)
            curveTo(34.28f, 4.34f, 33.68f, 4f, 33f, 4f)
            close()
        }
        path(fill = SolidColor(Color(0xFF8CCAF7))) {
            moveTo(31f, 22f)
            lineTo(31f, 9f)
            curveTo(31f, 8.45f, 30.55f, 8f, 30f, 8f)
            lineTo(6f, 8f)
            curveTo(5.45f, 8f, 5f, 8.45f, 5f, 9f)
            lineTo(5f, 22f)
            lineTo(31f, 22f)
            close()
        }
        path(fill = SolidColor(Color(0xFF5DADEC))) {
            moveTo(6f, 28f)
            lineTo(19f, 28f)
            lineTo(19f, 21f)
            lineTo(5f, 21f)
            lineTo(5f, 27f)
            curveTo(5f, 27.55f, 5.45f, 28f, 6f, 28f)
            close()
        }
        path(fill = SolidColor(Color(0xFF292F33))) {
            moveTo(19f, 21f)
            lineTo(19f, 28f)
            lineTo(30f, 28f)
            curveTo(30.55f, 28f, 31f, 27.55f, 31f, 27f)
            lineTo(31f, 21f)
            lineTo(19f, 21f)
            close()
        }
        path(fill = SolidColor(Color(0xFF67757F))) {
            moveTo(20f, 19f)
            curveTo(19.39f, 19f, 19.15f, 20.13f, 18.59f, 21f)
            curveTo(18.25f, 21.55f, 17.77f, 22f, 17f, 22f)
            curveTo(15f, 22f, 15f, 25f, 14f, 25f)
            curveTo(12.74f, 25f, 11.49f, 26.58f, 10.73f, 28f)
            lineTo(19f, 28f)
            curveTo(19.88f, 26.24f, 20.76f, 24.49f, 23f, 24.09f)
            curveTo(23.31f, 24.03f, 23.64f, 24f, 24f, 24f)
            curveTo(27f, 24f, 27.11f, 22.45f, 28f, 22f)
            curveTo(29.36f, 21.32f, 30.25f, 21.56f, 31f, 21.79f)
            lineTo(31f, 19f)
            lineTo(20f, 19f)
            close()
        }
        path(fill = SolidColor(Color(0xFFE75A70))) {
            moveTo(25f, 11f)
            lineTo(21f, 15f)
            lineTo(21f, 19f)
            lineTo(29f, 19f)
            lineTo(29f, 15f)
            close()
        }
        path(fill = SolidColor(Color(0xFF292F33))) {
            moveTo(29f, 16f)
            curveTo(28.74f, 16f, 28.49f, 15.9f, 28.29f, 15.71f)
            lineTo(25f, 12.41f)
            lineTo(21.71f, 15.71f)
            curveTo(21.32f, 16.1f, 20.68f, 16.1f, 20.29f, 15.71f)
            curveTo(19.9f, 15.32f, 19.9f, 14.68f, 20.29f, 14.29f)
            lineTo(24.29f, 10.29f)
            curveTo(24.68f, 9.9f, 25.32f, 9.9f, 25.71f, 10.29f)
            lineTo(29.71f, 14.29f)
            curveTo(30.1f, 14.68f, 30.1f, 15.32f, 29.71f, 15.71f)
            curveTo(29.51f, 15.9f, 29.26f, 16f, 29f, 16f)
            close()
        }
        path(fill = SolidColor(Color(0xFFBB1A34))) {
            moveTo(23f, 16f)
            lineTo(25f, 16f)
            lineTo(25f, 19f)
            lineTo(23f, 19f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF))) {
            moveTo(17.22f, 14.12f)
            curveTo(17.22f, 13.09f, 16.38f, 12.25f, 15.34f, 12.25f)
            curveTo(15.27f, 12.25f, 15.19f, 12.26f, 15.11f, 12.27f)
            curveTo(15.14f, 12.14f, 15.16f, 12.01f, 15.16f, 11.88f)
            curveTo(15.16f, 10.84f, 14.32f, 10f, 13.28f, 10f)
            curveTo(12.61f, 10f, 12.03f, 10.35f, 11.7f, 10.88f)
            curveTo(11.49f, 10.8f, 11.27f, 10.75f, 11.03f, 10.75f)
            curveTo(10.08f, 10.75f, 9.3f, 11.46f, 9.18f, 12.38f)
            curveTo(8.97f, 12.3f, 8.74f, 12.25f, 8.5f, 12.25f)
            curveTo(7.46f, 12.25f, 6.63f, 13.09f, 6.63f, 14.12f)
            curveTo(6.63f, 15.16f, 7.46f, 16f, 8.5f, 16f)
            curveTo(8.54f, 16f, 8.58f, 15.99f, 8.62f, 15.99f)
            lineTo(8.62f, 16f)
            lineTo(15.38f, 16f)
            lineTo(15.38f, 16f)
            curveTo(16.4f, 15.98f, 17.22f, 15.15f, 17.22f, 14.12f)
            close()
        }
    }.build()
}
