// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Grinning: ImageVector by lazy {
    ImageVector.Builder(
        name = "Grinning",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFF664500))) {
            moveTo(18f, 21f)
            curveTo(14.38f, 21f, 11.97f, 20.58f, 9f, 20f)
            curveTo(8.32f, 19.87f, 7f, 20f, 7f, 22f)
            curveTo(7f, 26f, 11.59f, 31f, 18f, 31f)
            curveTo(24.4f, 31f, 29f, 26f, 29f, 22f)
            curveTo(29f, 20f, 27.68f, 19.87f, 27f, 20f)
            curveTo(24.03f, 20.58f, 21.62f, 21f, 18f, 21f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF))) {
            moveTo(9f, 22f)
            curveTo(9f, 22f, 12f, 23f, 18f, 23f)
            curveTo(24f, 23f, 27f, 22f, 27f, 22f)
            curveTo(27f, 22f, 25f, 26f, 18f, 26f)
            curveTo(11f, 26f, 9f, 22f, 9f, 22f)
            close()
        }
    }.build()
}
