// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Heart: ImageVector by lazy {
    ImageVector.Builder(
        name = "Heart",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFDD2E44))) {
            moveTo(35.88f, 11.83f)
            curveTo(35.88f, 6.38f, 31.47f, 1.96f, 26.02f, 1.96f)
            curveTo(22.71f, 1.96f, 19.79f, 3.6f, 18f, 6.09f)
            curveTo(16.21f, 3.6f, 13.29f, 1.96f, 9.98f, 1.96f)
            curveTo(4.53f, 1.96f, 0.11f, 6.38f, 0.11f, 11.83f)
            curveTo(0.11f, 12.61f, 0.21f, 13.35f, 0.38f, 14.07f)
            curveTo(1.75f, 22.59f, 11.22f, 31.57f, 18f, 34.03f)
            curveTo(24.78f, 31.57f, 34.25f, 22.59f, 35.62f, 14.07f)
            curveTo(35.79f, 13.35f, 35.89f, 12.61f, 35.89f, 11.83f)
            close()
        }
    }.build()
}
