// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Herb: ImageVector by lazy {
    ImageVector.Builder(
        name = "Herb",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFF77B255))) {
            moveTo(20.92f, 22.5f)
            curveTo(18.21f, 22.17f, 17.02f, 20.65f, 14.64f, 17.61f)
            curveTo(17.68f, 15.24f, 19.2f, 14.05f, 21.91f, 14.38f)
            curveTo(24.62f, 14.71f, 27.16f, 16.39f, 28.18f, 19.27f)
            curveTo(26.5f, 21.81f, 23.63f, 22.83f, 20.92f, 22.5f)
            close()
            moveTo(14.96f, 31.32f)
            curveTo(12.41f, 31.13f, 11.23f, 29.76f, 8.86f, 27.03f)
            curveTo(11.6f, 24.66f, 12.96f, 23.48f, 15.51f, 23.66f)
            curveTo(18.06f, 23.85f, 20.52f, 25.31f, 21.61f, 27.95f)
            curveTo(20.15f, 30.41f, 17.51f, 31.5f, 14.96f, 31.32f)
            close()
            moveTo(8.74f, 15.61f)
            curveTo(10.08f, 17.24f, 9.93f, 18.73f, 9.64f, 21.7f)
            curveTo(6.67f, 21.4f, 5.18f, 21.26f, 3.84f, 19.63f)
            curveTo(2.5f, 17.99f, 1.98f, 15.69f, 2.94f, 13.54f)
            curveTo(5.24f, 13.01f, 7.4f, 13.98f, 8.74f, 15.61f)
            close()
            moveTo(29.85f, 10.16f)
            curveTo(27.42f, 11.18f, 25.69f, 10.47f, 22.24f, 9.06f)
            curveTo(23.65f, 5.61f, 24.36f, 3.88f, 26.79f, 2.86f)
            curveTo(29.22f, 1.84f, 32.17f, 2.03f, 34.4f, 3.96f)
            curveTo(34.21f, 6.9f, 32.29f, 9.14f, 29.85f, 10.16f)
            close()
            moveTo(17.1f, 6.61f)
            curveTo(17.98f, 9.48f, 16.98f, 11.35f, 14.98f, 15.1f)
            curveTo(11.24f, 13.1f, 9.37f, 12.1f, 8.49f, 9.23f)
            curveTo(7.61f, 6.36f, 8.18f, 3.05f, 10.61f, 0.74f)
            curveTo(13.92f, 1.3f, 16.23f, 3.73f, 17.1f, 6.61f)
            close()
        }
        path(fill = SolidColor(Color(0xFFA6D388))) {
            moveTo(8.49f, 9.23f)
            curveTo(9.35f, 12.06f, 11.19f, 13.07f, 14.83f, 15.01f)
            lineTo(14.83f, 15.01f)
            curveTo(14.76f, 12.49f, 12.09f, 4.13f, 10.56f, 0.79f)
            curveTo(8.17f, 3.1f, 7.62f, 6.38f, 8.49f, 9.23f)
            close()
            moveTo(2.9f, 13.66f)
            curveTo(2.01f, 15.78f, 2.53f, 18.02f, 3.84f, 19.63f)
            curveTo(5.18f, 21.26f, 6.67f, 21.4f, 9.64f, 21.7f)
            curveTo(8.64f, 19.76f, 4.73f, 15.31f, 2.9f, 13.66f)
            close()
        }
        path(fill = SolidColor(Color(0xFF5C913B))) {
            moveTo(21.91f, 14.38f)
            curveTo(19.35f, 14.07f, 17.83f, 15.13f, 15.1f, 17.26f)
            curveTo(16.85f, 17.36f, 23.89f, 18f, 28.16f, 19.29f)
            curveTo(28.17f, 19.28f, 28.18f, 19.28f, 28.18f, 19.27f)
            curveTo(27.16f, 16.39f, 24.62f, 14.71f, 21.91f, 14.38f)
            close()
            moveTo(21.61f, 27.94f)
            curveTo(20.52f, 25.31f, 18.06f, 23.85f, 15.51f, 23.66f)
            curveTo(13.01f, 23.48f, 11.64f, 24.62f, 9.01f, 26.9f)
            curveTo(11.78f, 26.59f, 16.92f, 26.03f, 21.61f, 27.94f)
            close()
        }
        path(fill = SolidColor(Color(0xFFA6D388))) {
            moveTo(22.42f, 9.14f)
            curveTo(25.75f, 10.5f, 27.46f, 11.16f, 29.85f, 10.16f)
            curveTo(32.27f, 9.14f, 34.19f, 6.92f, 34.4f, 4f)
            curveTo(30.47f, 4.76f, 24f, 8.15f, 22.42f, 9.14f)
            close()
        }
        path(fill = SolidColor(Color(0xFFA06253))) {
            moveTo(4.75f, 35.06f)
            curveTo(4.17f, 34.97f, 3.39f, 34.23f, 3.48f, 33.65f)
            curveTo(4.02f, 30.08f, 6.34f, 21.48f, 21.78f, 8.89f)
            curveTo(22.23f, 8.52f, 22.75f, 8.23f, 23.14f, 8.68f)
            curveTo(23.53f, 9.13f, 23.09f, 9.63f, 22.64f, 10.02f)
            curveTo(9.35f, 21.59f, 7.13f, 30.75f, 6.62f, 34.08f)
            curveTo(6.53f, 34.67f, 5.34f, 35.15f, 4.75f, 35.06f)
            close()
        }
    }.build()
}
