// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Hundred: ImageVector by lazy {
    ImageVector.Builder(
        name = "Hundred",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFBB1A34))) {
            moveTo(1.73f, 21f)
            curveTo(1.11f, 21f, 0.78f, 20.74f, 0.6f, 20.53f)
            curveTo(0.43f, 20.32f, 0.25f, 19.94f, 0.38f, 19.36f)
            lineTo(3.1f, 6.66f)
            lineTo(1.39f, 6.76f)
            lineTo(1.38f, 6.76f)
            curveTo(0.86f, 6.76f, 0.49f, 6.59f, 0.25f, 6.3f)
            curveTo(0.03f, 6.02f, -0.05f, 5.68f, 0.03f, 5.32f)
            curveTo(0.18f, 4.61f, 0.91f, 4.03f, 1.7f, 3.99f)
            lineTo(5.7f, 3.76f)
            curveTo(5.78f, 3.76f, 5.85f, 3.75f, 5.92f, 3.75f)
            curveTo(6.07f, 3.75f, 6.46f, 3.75f, 6.7f, 4.06f)
            curveTo(6.96f, 4.37f, 6.87f, 4.77f, 6.84f, 4.9f)
            lineTo(3.72f, 19.45f)
            curveTo(3.53f, 20.34f, 2.8f, 20.94f, 1.85f, 21f)
            lineTo(1.73f, 21f)
            close()
            moveTo(12.47f, 19f)
            curveTo(11.03f, 19f, 9.84f, 18.46f, 9.01f, 17.44f)
            curveTo(7.85f, 16f, 7.54f, 13.79f, 8.13f, 11.04f)
            curveTo(9.17f, 6.23f, 12.34f, 2.86f, 16.04f, 2.65f)
            curveTo(17.63f, 2.56f, 18.94f, 3.1f, 19.83f, 4.2f)
            curveTo(20.99f, 5.64f, 21.3f, 7.85f, 20.71f, 10.59f)
            curveTo(19.68f, 15.4f, 16.5f, 18.78f, 12.8f, 18.99f)
            curveTo(12.69f, 19f, 12.58f, 19f, 12.47f, 19f)
            close()
            moveTo(15.88f, 5.25f)
            lineTo(15.75f, 5.26f)
            curveTo(13.81f, 5.37f, 12.19f, 7.56f, 11.43f, 11.12f)
            curveTo(10.95f, 13.35f, 11.05f, 15.02f, 11.7f, 15.83f)
            curveTo(12f, 16.2f, 12.42f, 16.39f, 12.95f, 16.39f)
            lineTo(13.09f, 16.38f)
            curveTo(15.03f, 16.27f, 16.64f, 14.08f, 17.41f, 10.52f)
            curveTo(17.89f, 8.29f, 17.79f, 6.62f, 17.14f, 5.81f)
            curveTo(16.84f, 5.44f, 16.42f, 5.25f, 15.88f, 5.25f)
            close()
            moveTo(27.48f, 17.36f)
            curveTo(26.04f, 17.36f, 24.84f, 16.82f, 24.01f, 15.8f)
            curveTo(22.85f, 14.36f, 22.55f, 12.15f, 23.14f, 9.4f)
            curveTo(24.17f, 4.59f, 27.34f, 1.22f, 31.04f, 1.01f)
            curveTo(32.64f, 0.92f, 33.94f, 1.46f, 34.83f, 2.56f)
            curveTo(35.99f, 4f, 36.3f, 6.21f, 35.71f, 8.95f)
            curveTo(34.68f, 13.76f, 31.5f, 17.14f, 27.8f, 17.35f)
            curveTo(27.69f, 17.36f, 27.58f, 17.36f, 27.48f, 17.36f)
            close()
            moveTo(30.89f, 3.61f)
            lineTo(30.75f, 3.62f)
            curveTo(28.81f, 3.73f, 27.2f, 5.92f, 26.43f, 9.48f)
            curveTo(25.95f, 11.71f, 26.05f, 13.38f, 26.7f, 14.19f)
            curveTo(27f, 14.56f, 27.42f, 14.75f, 27.95f, 14.75f)
            lineTo(28.09f, 14.74f)
            curveTo(30.03f, 14.63f, 31.65f, 12.44f, 32.41f, 8.88f)
            curveTo(32.89f, 6.65f, 32.8f, 4.98f, 32.14f, 4.17f)
            curveTo(31.84f, 3.8f, 31.42f, 3.61f, 30.89f, 3.61f)
            close()
            moveTo(11f, 35f)
            curveTo(10.19f, 35f, 9.43f, 34.5f, 9.13f, 33.7f)
            curveTo(8.74f, 32.67f, 9.26f, 31.51f, 10.3f, 31.13f)
            curveTo(10.63f, 31f, 18.7f, 28.02f, 30.83f, 27.01f)
            curveTo(31.93f, 26.91f, 32.9f, 27.73f, 32.99f, 28.83f)
            curveTo(33.08f, 29.93f, 32.27f, 30.9f, 31.17f, 30.99f)
            curveTo(19.58f, 31.96f, 11.78f, 34.84f, 11.7f, 34.87f)
            curveTo(11.47f, 34.96f, 11.23f, 35f, 11f, 35f)
            close()
            moveTo(2f, 29f)
            curveTo(1.2f, 29f, 0.44f, 28.51f, 0.13f, 27.72f)
            curveTo(-0.26f, 26.69f, 0.25f, 25.53f, 1.28f, 25.13f)
            curveTo(1.82f, 24.93f, 14.8f, 20.01f, 33.89f, 19f)
            curveTo(35.01f, 18.93f, 35.94f, 19.79f, 36f, 20.89f)
            curveTo(36.06f, 22f, 35.21f, 22.94f, 34.1f, 23f)
            curveTo(15.68f, 23.97f, 2.84f, 28.82f, 2.72f, 28.87f)
            curveTo(2.48f, 28.96f, 2.24f, 29f, 2f, 29f)
            close()
        }
    }.build()
}
