// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Joy: ImageVector by lazy {
    ImageVector.Builder(
        name = "Joy",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFCC4D))) {
            moveTo(36f, 18f)
            curveTo(36f, 27.94f, 27.94f, 36f, 18f, 36f)
            curveTo(8.06f, 36f, 0f, 27.94f, 0f, 18f)
            curveTo(0f, 8.06f, 8.06f, 0f, 18f, 0f)
            curveTo(27.94f, 0f, 36f, 8.06f, 36f, 18f)
        }
        path(fill = SolidColor(Color(0xFF664500))) {
            moveTo(28.46f, 17.8f)
            curveTo(28.4f, 17.66f, 26.96f, 14.5f, 24f, 14.5f)
            curveTo(21.04f, 14.5f, 19.6f, 17.66f, 19.54f, 17.8f)
            curveTo(19.45f, 18f, 19.51f, 18.25f, 19.69f, 18.39f)
            curveTo(19.86f, 18.53f, 20.11f, 18.54f, 20.3f, 18.4f)
            curveTo(20.31f, 18.39f, 21.56f, 17.5f, 24f, 17.5f)
            curveTo(26.43f, 17.5f, 27.67f, 18.38f, 27.7f, 18.4f)
            curveTo(27.79f, 18.47f, 27.9f, 18.5f, 28f, 18.5f)
            curveTo(28.11f, 18.5f, 28.22f, 18.46f, 28.31f, 18.39f)
            curveTo(28.49f, 18.25f, 28.55f, 18f, 28.46f, 17.8f)
            close()
            moveTo(16.46f, 17.8f)
            curveTo(16.4f, 17.66f, 14.96f, 14.5f, 12f, 14.5f)
            curveTo(9.04f, 14.5f, 7.6f, 17.66f, 7.54f, 17.8f)
            curveTo(7.45f, 18f, 7.51f, 18.25f, 7.69f, 18.39f)
            curveTo(7.86f, 18.53f, 8.11f, 18.54f, 8.3f, 18.4f)
            curveTo(8.31f, 18.39f, 9.56f, 17.5f, 12f, 17.5f)
            curveTo(14.43f, 17.5f, 15.67f, 18.38f, 15.7f, 18.4f)
            curveTo(15.79f, 18.47f, 15.9f, 18.5f, 16f, 18.5f)
            curveTo(16.11f, 18.5f, 16.22f, 18.46f, 16.31f, 18.39f)
            curveTo(16.49f, 18.25f, 16.55f, 18f, 16.46f, 17.8f)
            close()
            moveTo(31f, 16f)
            curveTo(30.6f, 16f, 30.23f, 15.76f, 30.07f, 15.37f)
            curveTo(28.29f, 10.93f, 23.85f, 9.99f, 23.8f, 9.98f)
            curveTo(23.26f, 9.87f, 22.91f, 9.35f, 23.02f, 8.8f)
            curveTo(23.13f, 8.26f, 23.65f, 7.91f, 24.2f, 8.02f)
            curveTo(24.42f, 8.06f, 29.75f, 9.19f, 31.93f, 14.63f)
            curveTo(32.13f, 15.14f, 31.88f, 15.72f, 31.37f, 15.93f)
            curveTo(31.25f, 15.98f, 31.12f, 16f, 31f, 16f)
            close()
            moveTo(5f, 16f)
            curveTo(4.88f, 16f, 4.75f, 15.98f, 4.63f, 15.93f)
            curveTo(4.12f, 15.72f, 3.87f, 15.14f, 4.07f, 14.63f)
            curveTo(6.25f, 9.19f, 11.58f, 8.07f, 11.8f, 8.02f)
            curveTo(12.35f, 7.91f, 12.87f, 8.26f, 12.98f, 8.8f)
            curveTo(13.09f, 9.34f, 12.74f, 9.87f, 12.2f, 9.98f)
            curveTo(12.01f, 10.02f, 7.69f, 10.96f, 5.93f, 15.37f)
            curveTo(5.77f, 15.76f, 5.4f, 16f, 5f, 16f)
            close()
            moveTo(18f, 22f)
            curveTo(14.38f, 22f, 11.97f, 21.58f, 9f, 21f)
            curveTo(8.32f, 20.87f, 7f, 21f, 7f, 23f)
            curveTo(7f, 27f, 11.59f, 32f, 18f, 32f)
            curveTo(24.4f, 32f, 29f, 27f, 29f, 23f)
            curveTo(29f, 21f, 27.68f, 20.87f, 27f, 21f)
            curveTo(24.03f, 21.58f, 21.62f, 22f, 18f, 22f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFFFFF))) {
            moveTo(9f, 23f)
            curveTo(9f, 23f, 12f, 24f, 18f, 24f)
            curveTo(24f, 24f, 27f, 23f, 27f, 23f)
            curveTo(27f, 23f, 25f, 27f, 18f, 27f)
            curveTo(11f, 27f, 9f, 23f, 9f, 23f)
            close()
        }
        path(fill = SolidColor(Color(0xFF5DADEC))) {
            moveTo(10.85f, 28.23f)
            curveTo(10.17f, 30.91f, 7.45f, 32.52f, 4.77f, 31.84f)
            curveTo(2.09f, 31.17f, 0.47f, 28.45f, 1.15f, 25.77f)
            curveTo(1.83f, 23.09f, 7.49f, 17.06f, 8.46f, 17.31f)
            curveTo(9.43f, 17.55f, 11.53f, 25.55f, 10.85f, 28.23f)
            close()
            moveTo(25.13f, 28.23f)
            curveTo(25.81f, 30.91f, 28.53f, 32.52f, 31.21f, 31.84f)
            curveTo(33.89f, 31.17f, 35.51f, 28.45f, 34.83f, 25.77f)
            curveTo(34.15f, 23.09f, 28.49f, 17.06f, 27.52f, 17.31f)
            curveTo(26.55f, 17.55f, 24.45f, 25.55f, 25.13f, 28.23f)
            close()
        }
    }.build()
}
