// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val LoudlyCrying: ImageVector by lazy {
    ImageVector.Builder(
        name = "LoudlyCrying",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFCC4D))) {
            moveTo(36f, 18f)
            curveTo(36f, 27.94f, 27.94f, 36f, 18f, 36f)
            curveTo(8.06f, 36f, 0f, 27.94f, 0f, 18f)
            curveTo(0f, 8.06f, 8.06f, 0f, 18f, 0f)
            curveTo(27.94f, 0f, 36f, 8.06f, 36f, 18f)
        }
        path(fill = SolidColor(Color(0xFF664500))) {
            moveTo(22f, 27f)
            curveTo(22f, 29.76f, 20.21f, 30f, 18f, 30f)
            curveTo(15.79f, 30f, 14f, 29.76f, 14f, 27f)
            curveTo(14f, 24.24f, 15.79f, 21f, 18f, 21f)
            curveTo(20.21f, 21f, 22f, 24.24f, 22f, 27f)
            close()
            moveTo(30f, 15f)
            curveTo(29.88f, 15f, 29.75f, 14.98f, 29.63f, 14.93f)
            curveTo(24.4f, 12.84f, 22.26f, 9.69f, 22.17f, 9.55f)
            curveTo(21.86f, 9.09f, 21.98f, 8.47f, 22.45f, 8.17f)
            curveTo(22.9f, 7.86f, 23.52f, 7.98f, 23.83f, 8.44f)
            curveTo(23.85f, 8.47f, 25.76f, 11.23f, 30.37f, 13.07f)
            curveTo(30.88f, 13.28f, 31.13f, 13.86f, 30.93f, 14.37f)
            curveTo(30.77f, 14.76f, 30.4f, 15f, 30f, 15f)
            close()
            moveTo(6f, 15f)
            curveTo(5.6f, 15f, 5.23f, 14.76f, 5.07f, 14.37f)
            curveTo(4.87f, 13.86f, 5.11f, 13.28f, 5.63f, 13.07f)
            curveTo(10.24f, 11.23f, 12.15f, 8.47f, 12.17f, 8.44f)
            curveTo(12.48f, 7.99f, 13.1f, 7.87f, 13.56f, 8.17f)
            curveTo(14.01f, 8.48f, 14.14f, 9.1f, 13.83f, 9.55f)
            curveTo(13.74f, 9.69f, 11.6f, 12.84f, 6.37f, 14.93f)
            curveTo(6.25f, 14.98f, 6.12f, 15f, 6f, 15f)
            close()
        }
        path(fill = SolidColor(Color(0xFF5DADEC))) {
            moveTo(24f, 16f)
            lineTo(28f, 16f)
            lineTo(28f, 35f)
            lineTo(24f, 34.95f)
            lineTo(24f, 16f)
            close()
            moveTo(8f, 35f)
            lineTo(12f, 34.95f)
            lineTo(12f, 16f)
            lineTo(8f, 16f)
            lineTo(8f, 35f)
            close()
        }
        path(fill = SolidColor(Color(0xFF664500))) {
            moveTo(15f, 18f)
            curveTo(14.85f, 18f, 14.7f, 17.97f, 14.55f, 17.89f)
            curveTo(11.04f, 16.14f, 7.48f, 17.88f, 7.45f, 17.89f)
            curveTo(6.95f, 18.14f, 6.35f, 17.94f, 6.11f, 17.45f)
            curveTo(5.86f, 16.95f, 6.06f, 16.35f, 6.55f, 16.11f)
            curveTo(6.74f, 16.02f, 11.05f, 13.91f, 15.45f, 16.11f)
            curveTo(15.94f, 16.35f, 16.14f, 16.95f, 15.89f, 17.45f)
            curveTo(15.72f, 17.8f, 15.37f, 18f, 15f, 18f)
            close()
            moveTo(29f, 18f)
            curveTo(28.85f, 18f, 28.7f, 17.97f, 28.55f, 17.89f)
            curveTo(25.04f, 16.14f, 21.48f, 17.88f, 21.45f, 17.89f)
            curveTo(20.95f, 18.14f, 20.35f, 17.94f, 20.11f, 17.45f)
            curveTo(19.86f, 16.95f, 20.06f, 16.35f, 20.55f, 16.11f)
            curveTo(20.73f, 16.02f, 25.05f, 13.91f, 29.45f, 16.11f)
            curveTo(29.94f, 16.35f, 30.14f, 16.95f, 29.89f, 17.45f)
            curveTo(29.72f, 17.8f, 29.37f, 18f, 29f, 18f)
            close()
        }
    }.build()
}
