// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Man: ImageVector by lazy {
    ImageVector.Builder(
        name = "Man",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFDC5D))) {
            moveTo(8f, 19f)
            curveTo(8f, 21.21f, 6.88f, 23f, 5.5f, 23f)
            curveTo(4.12f, 23f, 3f, 21.21f, 3f, 19f)
            curveTo(3f, 16.79f, 4.12f, 15f, 5.5f, 15f)
            curveTo(6.88f, 15f, 8f, 16.79f, 8f, 19f)
            close()
            moveTo(33f, 19f)
            curveTo(33f, 21.21f, 31.88f, 23f, 30.5f, 23f)
            curveTo(29.12f, 23f, 28f, 21.21f, 28f, 19f)
            curveTo(28f, 16.79f, 29.12f, 15f, 30.5f, 15f)
            curveTo(31.88f, 15f, 33f, 16.79f, 33f, 19f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFDC5D))) {
            moveTo(5f, 20.56f)
            curveTo(5f, 12.04f, 10.82f, 5.12f, 18f, 5.12f)
            curveTo(25.18f, 5.12f, 31f, 12.04f, 31f, 20.56f)
            curveTo(31f, 29.09f, 25.18f, 36f, 18f, 36f)
            curveTo(10.82f, 36f, 5f, 29.09f, 5f, 20.56f)
            close()
        }
        path(fill = SolidColor(Color(0xFF662113))) {
            moveTo(13f, 20f)
            curveTo(12.45f, 20f, 12f, 19.55f, 12f, 19f)
            lineTo(12f, 17f)
            curveTo(12f, 16.45f, 12.45f, 16f, 13f, 16f)
            curveTo(13.55f, 16f, 14f, 16.45f, 14f, 17f)
            lineTo(14f, 19f)
            curveTo(14f, 19.55f, 13.55f, 20f, 13f, 20f)
            close()
            moveTo(23f, 20f)
            curveTo(22.45f, 20f, 22f, 19.55f, 22f, 19f)
            lineTo(22f, 17f)
            curveTo(22f, 16.45f, 22.45f, 16f, 23f, 16f)
            curveTo(23.55f, 16f, 24f, 16.45f, 24f, 17f)
            lineTo(24f, 19f)
            curveTo(24f, 19.55f, 23.55f, 20f, 23f, 20f)
            close()
        }
        path(fill = SolidColor(Color(0xFFC1694F))) {
            moveTo(19f, 24f)
            lineTo(17f, 24f)
            curveTo(16.45f, 24f, 16f, 23.55f, 16f, 23f)
            curveTo(16f, 22.45f, 16.45f, 22f, 17f, 22f)
            lineTo(19f, 22f)
            curveTo(19.55f, 22f, 20f, 22.45f, 20f, 23f)
            curveTo(20f, 23.55f, 19.55f, 24f, 19f, 24f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFAC33))) {
            moveTo(25.27f, 27.04f)
            lineTo(21.98f, 26.1f)
            curveTo(21.98f, 26.06f, 22f, 26.03f, 22f, 26f)
            curveTo(22f, 25.45f, 21.55f, 25f, 21f, 25f)
            lineTo(15f, 25f)
            curveTo(14.45f, 25f, 14f, 25.45f, 14f, 26f)
            curveTo(14f, 26.03f, 14.02f, 26.06f, 14.02f, 26.1f)
            lineTo(10.72f, 27.04f)
            curveTo(10.19f, 27.19f, 9.89f, 27.74f, 10.04f, 28.27f)
            curveTo(10.16f, 28.71f, 10.56f, 29f, 11f, 29f)
            curveTo(11.09f, 29f, 11.18f, 28.99f, 11.28f, 28.96f)
            lineTo(13.21f, 28.41f)
            curveTo(12.99f, 28.7f, 12.93f, 29.1f, 13.11f, 29.45f)
            curveTo(13.28f, 29.8f, 13.63f, 30f, 14f, 30f)
            curveTo(14.15f, 30f, 14.3f, 29.97f, 14.45f, 29.89f)
            lineTo(16.02f, 29.11f)
            curveTo(16.06f, 29.43f, 16.24f, 29.74f, 16.55f, 29.89f)
            curveTo(16.7f, 29.97f, 16.85f, 30f, 17f, 30f)
            curveTo(17.37f, 30f, 17.72f, 29.8f, 17.9f, 29.45f)
            lineTo(18f, 29.24f)
            lineTo(18.11f, 29.45f)
            curveTo(18.28f, 29.8f, 18.63f, 30f, 19f, 30f)
            curveTo(19.15f, 30f, 19.3f, 29.97f, 19.45f, 29.89f)
            curveTo(19.76f, 29.74f, 19.94f, 29.43f, 19.98f, 29.11f)
            lineTo(21.55f, 29.89f)
            curveTo(21.7f, 29.97f, 21.85f, 30f, 22f, 30f)
            curveTo(22.37f, 30f, 22.72f, 29.8f, 22.9f, 29.45f)
            curveTo(23.07f, 29.1f, 23.01f, 28.7f, 22.8f, 28.41f)
            lineTo(24.73f, 28.96f)
            curveTo(24.82f, 28.99f, 24.91f, 29f, 25f, 29f)
            curveTo(25.44f, 29f, 25.84f, 28.71f, 25.96f, 28.27f)
            curveTo(26.11f, 27.74f, 25.81f, 27.19f, 25.27f, 27.04f)
            close()
            moveTo(18f, 0f)
            curveTo(26.62f, 0f, 32f, 6.36f, 32f, 11.66f)
            curveTo(32f, 16.95f, 30.92f, 19.07f, 29.85f, 16.95f)
            lineTo(27.69f, 12.72f)
            curveTo(27.69f, 12.72f, 21.23f, 12.72f, 19.08f, 10.6f)
            curveTo(19.08f, 10.6f, 22.31f, 16.95f, 15.85f, 10.6f)
            curveTo(15.85f, 10.6f, 16.92f, 14.84f, 10.46f, 9.54f)
            curveTo(10.46f, 9.54f, 7.23f, 11.66f, 6.15f, 16.95f)
            curveTo(5.86f, 18.42f, 4f, 16.95f, 4f, 11.66f)
            curveTo(4f, 6.36f, 8.31f, 0f, 18f, 0f)
            close()
        }
    }.build()
}
