// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val OpenMailbox: ImageVector by lazy {
    ImageVector.Builder(
        name = "OpenMailbox",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFC1694F))) {
            moveTo(22f, 33f)
            curveTo(22f, 35.21f, 14f, 35.21f, 14f, 33f)
            lineTo(14f, 23f)
            curveTo(14f, 20.79f, 15.79f, 19f, 18f, 19f)
            curveTo(20.21f, 19f, 22f, 20.79f, 22f, 23f)
            lineTo(22f, 33f)
            close()
        }
        path(fill = SolidColor(Color(0xFF99AAB5))) {
            moveTo(26f, 3f)
            lineTo(10f, 3f)
            lineTo(10f, 23f)
            lineTo(34f, 23f)
            lineTo(34f, 11f)
            curveTo(34f, 6.58f, 30.42f, 3f, 26f, 3f)
            close()
        }
        path(fill = SolidColor(Color(0xFF292F33))) {
            moveTo(10f, 3f)
            curveTo(5.58f, 3f, 2f, 6.58f, 2f, 11f)
            lineTo(2f, 23f)
            lineTo(18f, 23f)
            lineTo(18f, 11f)
            curveTo(18f, 6.58f, 14.42f, 3f, 10f, 3f)
            close()
        }
        path(fill = SolidColor(Color(0xFFDD2E44))) {
            moveTo(34f, 13f)
            lineTo(22f, 13f)
            curveTo(20.9f, 13f, 20f, 13.9f, 20f, 15f)
            curveTo(20f, 16.1f, 20.9f, 17f, 22f, 17f)
            lineTo(30f, 17f)
            lineTo(30f, 19f)
            curveTo(30f, 20.1f, 30.9f, 21f, 32f, 21f)
            lineTo(34f, 21f)
            curveTo(35.1f, 21f, 36f, 20.1f, 36f, 19f)
            lineTo(36f, 15f)
            curveTo(36f, 13.9f, 35.1f, 13f, 34f, 13f)
            close()
        }
    }.build()
}
