// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Package: ImageVector by lazy {
    ImageVector.Builder(
        name = "Package",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFF662113))) {
            moveTo(4f, 11f)
            lineTo(4f, 23.38f)
            curveTo(4f, 25.42f, 5.09f, 25.86f, 5.09f, 25.86f)
            lineTo(16.67f, 34.96f)
            curveTo(18.49f, 36.39f, 18f, 33.38f, 18f, 33.38f)
            lineTo(18f, 22f)
            lineTo(4f, 11f)
            close()
        }
        path(fill = SolidColor(Color(0xFFC1694F))) {
            moveTo(32f, 11f)
            lineTo(32f, 23.38f)
            curveTo(32f, 25.42f, 30.94f, 25.86f, 30.94f, 25.86f)
            curveTo(30.94f, 25.86f, 21.17f, 33.53f, 19.35f, 34.96f)
            curveTo(17.53f, 36.39f, 18f, 33.38f, 18f, 33.38f)
            lineTo(18f, 22f)
            lineTo(32f, 11f)
            close()
        }
        path(fill = SolidColor(Color(0xFFD99E82))) {
            moveTo(19.29f, 0.5f)
            curveTo(18.54f, -0.11f, 17.3f, -0.11f, 16.55f, 0.5f)
            lineTo(4.57f, 10.03f)
            curveTo(3.81f, 10.64f, 3.81f, 11.64f, 4.57f, 12.25f)
            lineTo(16.59f, 21.89f)
            curveTo(17.34f, 22.5f, 18.58f, 22.5f, 19.33f, 21.89f)
            lineTo(31.43f, 12.16f)
            curveTo(32.19f, 11.55f, 32.19f, 10.56f, 31.43f, 9.95f)
            lineTo(19.29f, 0.5f)
            close()
        }
        path(fill = SolidColor(Color(0xFFD99E82))) {
            moveTo(18f, 35.75f)
            curveTo(17.45f, 35.75f, 17f, 35.27f, 17f, 34.67f)
            lineTo(17f, 21.75f)
            curveTo(17f, 21.15f, 17.45f, 20.67f, 18f, 20.67f)
            curveTo(18.55f, 20.67f, 19f, 21.15f, 19f, 21.75f)
            lineTo(19f, 34.67f)
            curveTo(19f, 35.27f, 18.55f, 35.75f, 18f, 35.75f)
            close()
        }
        path(fill = SolidColor(Color(0xFF99AAB5))) {
            moveTo(28f, 18.84f)
            curveTo(28f, 19.94f, 28.1f, 20.48f, 27f, 21.28f)
            lineTo(24.53f, 23.16f)
            curveTo(23.43f, 23.95f, 23f, 23.27f, 23f, 22.16f)
            lineTo(23f, 19.2f)
            curveTo(23f, 19.01f, 22.97f, 18.8f, 22.72f, 18.59f)
            curveTo(20.14f, 16.47f, 10.13f, 8.52f, 8.31f, 7.05f)
            lineTo(12.94f, 3.37f)
            curveTo(14.2f, 4.3f, 23.69f, 11.62f, 27.66f, 14.75f)
            curveTo(27.85f, 14.91f, 28f, 15.08f, 28f, 15.27f)
            lineTo(28f, 18.84f)
            close()
        }
        path(fill = SolidColor(Color(0xFFCCD6DD))) {
            moveTo(27.66f, 14.75f)
            curveTo(23.69f, 11.62f, 14.2f, 4.3f, 12.94f, 3.37f)
            lineTo(11.21f, 4.74f)
            lineTo(8.31f, 7.05f)
            curveTo(10.13f, 8.52f, 20.14f, 16.47f, 22.72f, 18.59f)
            curveTo(22.87f, 18.72f, 22.94f, 18.84f, 22.97f, 18.97f)
            lineTo(27.9f, 15f)
            curveTo(27.84f, 14.91f, 27.76f, 14.83f, 27.66f, 14.75f)
            close()
        }
        path(fill = SolidColor(Color(0xFFCCD6DD))) {
            moveTo(28f, 18.84f)
            lineTo(28f, 15.27f)
            curveTo(28f, 15.08f, 27.85f, 14.91f, 27.66f, 14.75f)
            curveTo(23.69f, 11.62f, 14.2f, 4.3f, 12.93f, 3.37f)
            lineTo(10.86f, 5.02f)
            curveTo(14.25f, 7.69f, 23.34f, 14.7f, 25.72f, 16.59f)
            curveTo(25.98f, 16.8f, 26f, 17.01f, 26f, 17.2f)
            lineTo(26f, 22.04f)
            lineTo(27f, 21.28f)
            curveTo(28.1f, 20.48f, 28f, 19.94f, 28f, 18.84f)
            close()
        }
        path(fill = SolidColor(Color(0xFFE1E8ED))) {
            moveTo(27.66f, 14.75f)
            curveTo(23.69f, 11.62f, 14.2f, 4.3f, 12.94f, 3.37f)
            lineTo(10.86f, 5.02f)
            curveTo(14.25f, 7.69f, 23.34f, 14.7f, 25.72f, 16.59f)
            curveTo(25.76f, 16.62f, 25.78f, 16.65f, 25.81f, 16.68f)
            lineTo(27.9f, 15f)
            curveTo(27.84f, 14.91f, 27.76f, 14.83f, 27.66f, 14.75f)
            close()
        }
    }.build()
}
