// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PageFacingUp: ImageVector by lazy {
    ImageVector.Builder(
        name = "PageFacingUp",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFE1E8ED))) {
            moveTo(32.41f, 9.59f)
            lineTo(23.41f, 0.59f)
            curveTo(23.05f, 0.23f, 22.55f, 0f, 22f, 0f)
            curveTo(20.9f, 0f, 20f, 0.9f, 20f, 2f)
            curveTo(20f, 2.55f, 20.22f, 3.05f, 20.59f, 3.42f)
            lineTo(16.73f, 7.27f)
            lineTo(25.73f, 16.27f)
            lineTo(29.59f, 12.42f)
            curveTo(29.95f, 12.78f, 30.45f, 13f, 31f, 13f)
            curveTo(32.1f, 13f, 33f, 12.1f, 33f, 11f)
            curveTo(33f, 10.45f, 32.78f, 9.95f, 32.41f, 9.59f)
            close()
        }
        path(fill = SolidColor(Color(0xFFCCD6DD))) {
            moveTo(22f, 0f)
            lineTo(7f, 0f)
            curveTo(4.79f, 0f, 3f, 1.79f, 3f, 4f)
            lineTo(3f, 32f)
            curveTo(3f, 34.21f, 4.79f, 36f, 7f, 36f)
            lineTo(29f, 36f)
            curveTo(31.21f, 36f, 33f, 34.21f, 33f, 32f)
            lineTo(33f, 11f)
            lineTo(24f, 11f)
            curveTo(23f, 11f, 22f, 10f, 22f, 9f)
            lineTo(22f, 0f)
            close()
        }
        path(fill = SolidColor(Color(0xFF99AAB5))) {
            moveTo(22f, 0f)
            lineTo(20f, 0f)
            lineTo(20f, 9f)
            curveTo(20f, 11.21f, 21.79f, 13f, 24f, 13f)
            lineTo(33f, 13f)
            lineTo(33f, 11f)
            lineTo(24f, 11f)
            curveTo(23f, 11f, 22f, 10f, 22f, 9f)
            lineTo(22f, 0f)
            close()
            moveTo(17f, 8f)
            curveTo(17f, 8.55f, 16.55f, 9f, 16f, 9f)
            lineTo(8f, 9f)
            curveTo(7.45f, 9f, 7f, 8.55f, 7f, 8f)
            curveTo(7f, 7.45f, 7.45f, 7f, 8f, 7f)
            lineTo(16f, 7f)
            curveTo(16.55f, 7f, 17f, 7.45f, 17f, 8f)
            close()
            moveTo(17f, 12f)
            curveTo(17f, 12.55f, 16.55f, 13f, 16f, 13f)
            lineTo(8f, 13f)
            curveTo(7.45f, 13f, 7f, 12.55f, 7f, 12f)
            curveTo(7f, 11.45f, 7.45f, 11f, 8f, 11f)
            lineTo(16f, 11f)
            curveTo(16.55f, 11f, 17f, 11.45f, 17f, 12f)
            close()
            moveTo(29f, 16f)
            curveTo(29f, 16.55f, 28.55f, 17f, 28f, 17f)
            lineTo(8f, 17f)
            curveTo(7.45f, 17f, 7f, 16.55f, 7f, 16f)
            curveTo(7f, 15.45f, 7.45f, 15f, 8f, 15f)
            lineTo(28f, 15f)
            curveTo(28.55f, 15f, 29f, 15.45f, 29f, 16f)
            close()
            moveTo(29f, 20f)
            curveTo(29f, 20.55f, 28.55f, 21f, 28f, 21f)
            lineTo(8f, 21f)
            curveTo(7.45f, 21f, 7f, 20.55f, 7f, 20f)
            curveTo(7f, 19.45f, 7.45f, 19f, 8f, 19f)
            lineTo(28f, 19f)
            curveTo(28.55f, 19f, 29f, 19.45f, 29f, 20f)
            close()
            moveTo(29f, 24f)
            curveTo(29f, 24.55f, 28.55f, 25f, 28f, 25f)
            lineTo(8f, 25f)
            curveTo(7.45f, 25f, 7f, 24.55f, 7f, 24f)
            curveTo(7f, 23.45f, 7.45f, 23f, 8f, 23f)
            lineTo(28f, 23f)
            curveTo(28.55f, 23f, 29f, 23.45f, 29f, 24f)
            close()
            moveTo(29f, 28f)
            curveTo(29f, 28.55f, 28.55f, 29f, 28f, 29f)
            lineTo(8f, 29f)
            curveTo(7.45f, 29f, 7f, 28.55f, 7f, 28f)
            curveTo(7f, 27.45f, 7.45f, 27f, 8f, 27f)
            lineTo(28f, 27f)
            curveTo(28.55f, 27f, 29f, 27.45f, 29f, 28f)
            close()
        }
    }.build()
}
