// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PrayHands: ImageVector by lazy {
    ImageVector.Builder(
        name = "PrayHands",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFF50A5E6))) {
            moveTo(30f, 22f)
            curveTo(27f, 22f, 23.31f, 29.09f, 23f, 32f)
            curveTo(22.58f, 35.91f, 25f, 36f, 25f, 36f)
            lineTo(36f, 36f)
            lineTo(36f, 26f)
            curveTo(36f, 26f, 32.56f, 22f, 30f, 22f)
            close()
        }
        path(fill = SolidColor(Color(0xFFF9CA55))) {
            moveTo(20.09f, 0f)
            curveTo(21.27f, 0f, 22.22f, 0.96f, 22.22f, 2.14f)
            curveTo(22.22f, 2.93f, 22.89f, 12.96f, 22.89f, 12.96f)
            lineTo(17.95f, 18f)
            lineTo(17.95f, 2.14f)
            curveTo(17.95f, 0.96f, 18.91f, 0f, 20.09f, 0f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFDC5D))) {
            moveTo(18.88f, 4.32f)
            curveTo(18.88f, 3.22f, 19.73f, 2.33f, 20.78f, 2.33f)
            curveTo(21.83f, 2.33f, 22.68f, 3.23f, 22.68f, 4.32f)
            curveTo(22.68f, 4.32f, 23.22f, 10.27f, 23.87f, 13.69f)
            curveTo(24.75f, 15.56f, 25.24f, 18.38f, 25.13f, 19.94f)
            curveTo(25.19f, 20.34f, 30.76f, 24.95f, 30.76f, 24.95f)
            curveTo(30.48f, 26.76f, 28.5f, 31.1f, 26f, 33.11f)
            lineTo(22.48f, 30.18f)
            curveTo(19.59f, 29.78f, 18.02f, 26.85f, 18.02f, 25.92f)
            curveTo(18.02f, 22.93f, 18.87f, 4.32f, 18.87f, 4.32f)
            close()
        }
        path(fill = SolidColor(Color(0xFF50A5E6))) {
            moveTo(6f, 22f)
            curveTo(9f, 22f, 12.69f, 29.09f, 13f, 32f)
            curveTo(13.42f, 35.91f, 11f, 36f, 11f, 36f)
            lineTo(0f, 36f)
            lineTo(0f, 26f)
            curveTo(0f, 26f, 3.44f, 22f, 6f, 22f)
            close()
        }
        path(fill = SolidColor(Color(0xFFF9CA55))) {
            moveTo(16.06f, 0.01f)
            curveTo(14.79f, -0.12f, 13.73f, 0.88f, 13.73f, 2.11f)
            curveTo(13.73f, 2.89f, 13.54f, 12.43f, 13.54f, 12.43f)
            lineTo(17.89f, 18f)
            lineTo(17.96f, 2.23f)
            curveTo(17.96f, 1.13f, 17.16f, 0.12f, 16.06f, 0.01f)
            close()
        }
        path(fill = SolidColor(Color(0xFFFFDC5D))) {
            moveTo(17.12f, 4.32f)
            curveTo(17.12f, 3.22f, 16.27f, 2.33f, 15.22f, 2.33f)
            curveTo(14.17f, 2.33f, 13.32f, 3.23f, 13.32f, 4.32f)
            curveTo(13.32f, 4.32f, 12.78f, 10.27f, 12.13f, 13.69f)
            curveTo(11.25f, 15.56f, 10.76f, 18.38f, 10.87f, 19.94f)
            curveTo(10.81f, 20.34f, 5.24f, 24.95f, 5.24f, 24.95f)
            curveTo(5.52f, 26.76f, 7.5f, 31.1f, 10f, 33.11f)
            lineTo(13.52f, 30.18f)
            curveTo(16.41f, 29.78f, 17.98f, 26.85f, 17.98f, 25.92f)
            curveTo(17.98f, 22.93f, 17.12f, 4.32f, 17.12f, 4.32f)
            close()
        }
        path(fill = SolidColor(Color(0xFFF9CA55))) {
            moveTo(17.96f, 25.82f)
            curveTo(17.54f, 25.82f, 17.21f, 25.49f, 17.21f, 25.07f)
            lineTo(17.21f, 2.79f)
            curveTo(17.21f, 2.38f, 17.54f, 2.04f, 17.96f, 2.04f)
            curveTo(18.37f, 2.04f, 18.71f, 2.38f, 18.71f, 2.79f)
            lineTo(18.71f, 25.07f)
            curveTo(18.71f, 25.49f, 18.37f, 25.82f, 17.96f, 25.82f)
            close()
        }
    }.build()
}
