// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Pushpin: ImageVector by lazy {
    ImageVector.Builder(
        name = "Pushpin",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFBE1931))) {
            moveTo(23.65f, 23.3f)
            lineTo(12.7f, 12.35f)
            lineTo(22.09f, 4.53f)
            lineTo(31.47f, 13.91f)
            close()
        }
        path(fill = SolidColor(Color(0xFFDD2E44))) {
            moveTo(34.6f, 13.91f)
            curveTo(32.87f, 15.64f, 30.07f, 15.64f, 28.35f, 13.91f)
            lineTo(22.09f, 7.66f)
            curveTo(20.36f, 5.93f, 20.36f, 3.13f, 22.09f, 1.4f)
            curveTo(23.81f, -0.33f, 26.62f, -0.33f, 28.34f, 1.4f)
            lineTo(34.6f, 7.66f)
            curveTo(36.33f, 9.38f, 36.33f, 12.18f, 34.6f, 13.91f)
            close()
        }
        path(fill = SolidColor(Color(0xFF99AAB5))) {
            moveTo(14f, 17.82f)
            curveTo(14f, 17.82f, -0.59f, 35.03f, 0.19f, 35.81f)
            curveTo(0.97f, 36.6f, 18.18f, 22f, 18.18f, 22f)
            lineTo(14f, 17.82f)
            close()
        }
        path(fill = SolidColor(Color(0xFFDD2E44))) {
            moveTo(25.21f, 27.99f)
            curveTo(23.49f, 29.72f, 20.69f, 29.72f, 18.96f, 27.99f)
            lineTo(8.01f, 17.04f)
            curveTo(6.28f, 15.31f, 6.28f, 12.51f, 8.01f, 10.79f)
            curveTo(9.74f, 9.06f, 12.54f, 9.06f, 14.27f, 10.79f)
            lineTo(25.21f, 21.73f)
            curveTo(26.94f, 23.46f, 26.94f, 26.26f, 25.21f, 27.99f)
            close()
        }
    }.build()
}
