// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val SlightlySmiling: ImageVector by lazy {
    ImageVector.Builder(
        name = "SlightlySmiling",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFF664500))) {
            moveTo(10.52f, 23.62f)
            curveTo(10.56f, 23.8f, 11.68f, 28f, 18f, 28f)
            curveTo(24.32f, 28f, 25.44f, 23.8f, 25.48f, 23.62f)
            curveTo(25.54f, 23.4f, 25.44f, 23.18f, 25.25f, 23.07f)
            curveTo(25.05f, 22.96f, 24.81f, 22.99f, 24.65f, 23.14f)
            curveTo(24.63f, 23.16f, 22.69f, 25f, 18f, 25f)
            curveTo(13.31f, 25f, 11.37f, 23.16f, 11.35f, 23.14f)
            curveTo(11.26f, 23.05f, 11.13f, 23f, 11f, 23f)
            curveTo(10.92f, 23f, 10.83f, 23.02f, 10.75f, 23.06f)
            curveTo(10.56f, 23.18f, 10.46f, 23.4f, 10.51f, 23.62f)
            close()
        }
    }.build()
}
