// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Tada: ImageVector by lazy {
    ImageVector.Builder(
        name = "Tada",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFDD2E44))) {
            moveTo(11.63f, 7.49f)
            curveTo(11.51f, 7.6f, 11.43f, 7.74f, 11.36f, 7.88f)
            lineTo(11.35f, 7.88f)
            lineTo(0.13f, 33.14f)
            lineTo(0.15f, 33.15f)
            curveTo(-0.06f, 33.55f, 0.29f, 34.38f, 1f, 35.09f)
            curveTo(1.71f, 35.8f, 2.53f, 36.15f, 2.93f, 35.94f)
            lineTo(2.94f, 35.95f)
            lineTo(28.21f, 24.73f)
            lineTo(28.2f, 24.73f)
            curveTo(28.35f, 24.66f, 28.48f, 24.57f, 28.6f, 24.46f)
            curveTo(30.16f, 22.89f, 27.63f, 17.83f, 22.94f, 13.14f)
            curveTo(18.25f, 8.46f, 13.19f, 5.93f, 11.63f, 7.49f)
            close()
        }
        path(fill = SolidColor(Color(0xFFEA596E))) {
            moveTo(13f, 12f)
            lineTo(0.42f, 32.51f)
            lineTo(0.13f, 33.14f)
            lineTo(0.15f, 33.15f)
            curveTo(-0.06f, 33.55f, 0.29f, 34.38f, 1f, 35.09f)
            curveTo(1.23f, 35.32f, 1.47f, 35.5f, 1.71f, 35.65f)
            lineTo(17f, 17f)
            lineTo(13f, 12f)
            close()
        }
        path(fill = SolidColor(Color(0xFFA0041E))) {
            moveTo(23.01f, 13.07f)
            curveTo(27.68f, 17.74f, 30.27f, 22.72f, 28.8f, 24.19f)
            curveTo(27.33f, 25.66f, 22.35f, 23.07f, 17.68f, 18.4f)
            curveTo(13f, 13.73f, 10.41f, 8.75f, 11.89f, 7.28f)
            curveTo(13.36f, 5.8f, 18.34f, 8.39f, 23.01f, 13.07f)
            close()
        }
        path(fill = SolidColor(Color(0xFFAA8DD8))) {
            moveTo(18.59f, 13.61f)
            curveTo(18.39f, 13.77f, 18.13f, 13.85f, 17.86f, 13.82f)
            curveTo(16.99f, 13.73f, 16.26f, 13.43f, 15.75f, 12.95f)
            curveTo(15.21f, 12.45f, 14.94f, 11.77f, 15.01f, 11.09f)
            curveTo(15.14f, 9.9f, 16.34f, 8.8f, 18.38f, 9.02f)
            curveTo(19.17f, 9.11f, 19.52f, 8.85f, 19.53f, 8.73f)
            curveTo(19.55f, 8.61f, 19.26f, 8.29f, 18.46f, 8.2f)
            curveTo(17.6f, 8.11f, 16.87f, 7.8f, 16.35f, 7.33f)
            curveTo(15.81f, 6.82f, 15.55f, 6.14f, 15.62f, 5.46f)
            curveTo(15.75f, 4.27f, 16.94f, 3.18f, 18.98f, 3.4f)
            curveTo(19.56f, 3.46f, 19.86f, 3.34f, 19.99f, 3.26f)
            curveTo(20.1f, 3.2f, 20.14f, 3.14f, 20.14f, 3.11f)
            curveTo(20.15f, 2.99f, 19.87f, 2.66f, 19.07f, 2.57f)
            curveTo(18.52f, 2.51f, 18.12f, 2.02f, 18.19f, 1.47f)
            curveTo(18.24f, 0.92f, 18.74f, 0.53f, 19.29f, 0.59f)
            curveTo(21.32f, 0.81f, 22.26f, 2.13f, 22.13f, 3.32f)
            curveTo(22f, 4.52f, 20.81f, 5.61f, 18.77f, 5.39f)
            curveTo(18.19f, 5.33f, 17.89f, 5.45f, 17.76f, 5.52f)
            curveTo(17.65f, 5.58f, 17.61f, 5.65f, 17.61f, 5.68f)
            curveTo(17.59f, 5.8f, 17.88f, 6.13f, 18.68f, 6.21f)
            curveTo(20.71f, 6.43f, 21.65f, 7.75f, 21.52f, 8.95f)
            curveTo(21.39f, 10.14f, 20.2f, 11.23f, 18.16f, 11.01f)
            curveTo(17.58f, 10.95f, 17.28f, 11.07f, 17.15f, 11.15f)
            curveTo(17.04f, 11.21f, 17f, 11.27f, 17f, 11.3f)
            curveTo(16.99f, 11.42f, 17.28f, 11.75f, 18.07f, 11.84f)
            curveTo(18.62f, 11.9f, 19.02f, 12.39f, 18.96f, 12.94f)
            curveTo(18.93f, 13.21f, 18.79f, 13.45f, 18.59f, 13.61f)
            close()
        }
        path(fill = SolidColor(Color(0xFF77B255))) {
            moveTo(30.66f, 22.86f)
            curveTo(32.63f, 22.3f, 34f, 23.18f, 34.32f, 24.34f)
            curveTo(34.64f, 25.49f, 33.94f, 26.95f, 31.97f, 27.51f)
            curveTo(31.2f, 27.72f, 30.97f, 28.09f, 31f, 28.21f)
            curveTo(31.03f, 28.32f, 31.42f, 28.52f, 32.19f, 28.3f)
            curveTo(34.16f, 27.75f, 35.52f, 28.63f, 35.85f, 29.78f)
            curveTo(36.18f, 30.94f, 35.47f, 32.39f, 33.5f, 32.95f)
            curveTo(32.73f, 33.17f, 32.5f, 33.54f, 32.53f, 33.65f)
            curveTo(32.56f, 33.77f, 32.95f, 33.96f, 33.72f, 33.75f)
            curveTo(34.25f, 33.6f, 34.81f, 33.91f, 34.96f, 34.44f)
            curveTo(35.1f, 34.97f, 34.8f, 35.52f, 34.26f, 35.67f)
            curveTo(32.29f, 36.23f, 30.93f, 35.35f, 30.6f, 34.19f)
            curveTo(30.28f, 33.04f, 30.98f, 31.58f, 32.96f, 31.02f)
            curveTo(33.73f, 30.81f, 33.96f, 30.44f, 33.92f, 30.32f)
            curveTo(33.89f, 30.21f, 33.5f, 30.01f, 32.73f, 30.23f)
            curveTo(30.76f, 30.78f, 29.4f, 29.9f, 29.08f, 28.75f)
            curveTo(28.75f, 27.59f, 29.45f, 26.13f, 31.43f, 25.58f)
            curveTo(32.19f, 25.36f, 32.43f, 24.99f, 32.39f, 24.88f)
            curveTo(32.36f, 24.76f, 31.97f, 24.56f, 31.2f, 24.78f)
            curveTo(30.67f, 24.93f, 30.12f, 24.62f, 29.97f, 24.09f)
            curveTo(29.82f, 23.56f, 30.13f, 23.01f, 30.66f, 22.86f)
            close()
        }
        path(fill = SolidColor(Color(0xFFAA8DD8))) {
            moveTo(23f, 20.16f)
            curveTo(22.71f, 20.16f, 22.42f, 20.03f, 22.22f, 19.79f)
            curveTo(21.87f, 19.35f, 21.95f, 18.72f, 22.38f, 18.38f)
            curveTo(22.59f, 18.2f, 27.79f, 14.12f, 35.14f, 15.17f)
            curveTo(35.69f, 15.25f, 36.07f, 15.76f, 35.99f, 16.3f)
            curveTo(35.91f, 16.85f, 35.41f, 17.23f, 34.86f, 17.15f)
            curveTo(28.37f, 16.23f, 23.67f, 19.9f, 23.63f, 19.94f)
            curveTo(23.44f, 20.09f, 23.22f, 20.16f, 23f, 20.16f)
            close()
        }
        path(fill = SolidColor(Color(0xFF77B255))) {
            moveTo(5.75f, 16f)
            curveTo(5.66f, 16f, 5.56f, 15.99f, 5.47f, 15.96f)
            curveTo(4.94f, 15.8f, 4.64f, 15.24f, 4.8f, 14.71f)
            curveTo(5.93f, 10.94f, 6.96f, 4.92f, 5.69f, 3.35f)
            curveTo(5.55f, 3.17f, 5.34f, 3f, 4.85f, 3.03f)
            curveTo(3.91f, 3.11f, 4f, 5.08f, 4f, 5.1f)
            curveTo(4.05f, 5.66f, 3.63f, 6.14f, 3.08f, 6.18f)
            curveTo(2.52f, 6.21f, 2.05f, 5.8f, 2.01f, 5.25f)
            curveTo(1.91f, 3.87f, 2.34f, 1.22f, 4.7f, 1.04f)
            curveTo(5.76f, 0.96f, 6.63f, 1.33f, 7.25f, 2.1f)
            curveTo(9.62f, 5.05f, 7.22f, 13.6f, 6.71f, 15.29f)
            curveTo(6.58f, 15.72f, 6.18f, 16f, 5.75f, 16f)
            close()
        }
    }.build()
}
