// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ThumbsUp: ImageVector by lazy {
    ImageVector.Builder(
        name = "ThumbsUp",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFDB5E))) {
            moveTo(34.96f, 17.92f)
            curveTo(34.96f, 17.41f, 34.84f, 16.94f, 34.64f, 16.51f)
            curveTo(33.29f, 12.19f, 27.02f, 12.5f, 18.09f, 12.29f)
            curveTo(16.59f, 12.26f, 17.45f, 10.49f, 17.97f, 6.62f)
            curveTo(18.31f, 4.11f, 16.69f, 0.24f, 13.96f, 0.24f)
            curveTo(9.46f, 0.24f, 13.79f, 3.79f, 9.81f, 12.56f)
            curveTo(7.69f, 17.25f, 2.94f, 14.62f, 2.94f, 19.33f)
            lineTo(2.94f, 30.05f)
            curveTo(2.94f, 31.89f, 3.12f, 33.65f, 5.7f, 33.94f)
            curveTo(8.2f, 34.22f, 7.63f, 36f, 11.24f, 36f)
            lineTo(29.28f, 36f)
            curveTo(31.12f, 36f, 32.62f, 34.5f, 32.62f, 32.67f)
            curveTo(32.62f, 31.9f, 32.35f, 31.21f, 31.92f, 30.65f)
            curveTo(32.94f, 30.08f, 33.64f, 29f, 33.64f, 27.75f)
            curveTo(33.64f, 26.99f, 33.37f, 26.29f, 32.94f, 25.73f)
            curveTo(33.96f, 25.16f, 34.67f, 24.08f, 34.67f, 22.83f)
            curveTo(34.67f, 21.92f, 34.3f, 21.1f, 33.71f, 20.5f)
            curveTo(34.46f, 19.89f, 34.96f, 18.96f, 34.96f, 17.92f)
            close()
        }
        path(fill = SolidColor(Color(0xFFEE9547))) {
            moveTo(23.02f, 21.25f)
            lineTo(31.62f, 21.25f)
            curveTo(32.79f, 21.25f, 33.89f, 20.62f, 34.49f, 19.62f)
            curveTo(34.74f, 19.2f, 34.6f, 18.66f, 34.18f, 18.42f)
            curveTo(33.77f, 18.17f, 33.23f, 18.31f, 32.98f, 18.72f)
            curveTo(32.7f, 19.2f, 32.18f, 19.5f, 31.62f, 19.5f)
            lineTo(22.81f, 19.5f)
            curveTo(21.94f, 19.5f, 21.23f, 18.79f, 21.23f, 17.92f)
            curveTo(21.23f, 17.04f, 21.94f, 16.33f, 22.81f, 16.33f)
            lineTo(28.7f, 16.33f)
            curveTo(29.18f, 16.33f, 29.57f, 15.94f, 29.57f, 15.46f)
            curveTo(29.57f, 14.97f, 29.18f, 14.58f, 28.7f, 14.58f)
            lineTo(22.81f, 14.58f)
            curveTo(20.97f, 14.58f, 19.48f, 16.08f, 19.48f, 17.92f)
            curveTo(19.48f, 18.94f, 19.95f, 19.85f, 20.68f, 20.46f)
            curveTo(20.07f, 21.06f, 19.69f, 21.9f, 19.69f, 22.83f)
            curveTo(19.69f, 23.86f, 20.16f, 24.77f, 20.9f, 25.38f)
            curveTo(20.29f, 25.99f, 19.91f, 26.82f, 19.91f, 27.75f)
            curveTo(19.91f, 28.87f, 20.47f, 29.86f, 21.32f, 30.46f)
            curveTo(20.79f, 31.05f, 20.46f, 31.82f, 20.46f, 32.67f)
            curveTo(20.46f, 34.5f, 21.96f, 36f, 23.8f, 36f)
            lineTo(29.28f, 36f)
            curveTo(30.45f, 36f, 31.55f, 35.37f, 32.15f, 34.37f)
            curveTo(32.4f, 33.95f, 32.26f, 33.41f, 31.84f, 33.17f)
            curveTo(31.43f, 32.92f, 30.89f, 33.06f, 30.64f, 33.47f)
            curveTo(30.36f, 33.95f, 29.84f, 34.25f, 29.28f, 34.25f)
            lineTo(23.8f, 34.25f)
            curveTo(22.92f, 34.25f, 22.21f, 33.54f, 22.21f, 32.67f)
            curveTo(22.21f, 31.79f, 22.92f, 31.08f, 23.8f, 31.08f)
            lineTo(30.3f, 31.08f)
            curveTo(31.47f, 31.08f, 32.57f, 30.46f, 33.17f, 29.45f)
            curveTo(33.42f, 29.03f, 33.28f, 28.5f, 32.87f, 28.25f)
            curveTo(32.45f, 28f, 31.91f, 28.14f, 31.67f, 28.56f)
            curveTo(31.38f, 29.04f, 30.87f, 29.33f, 30.3f, 29.33f)
            lineTo(23.24f, 29.33f)
            curveTo(22.37f, 29.33f, 21.66f, 28.62f, 21.66f, 27.75f)
            curveTo(21.66f, 26.88f, 22.37f, 26.17f, 23.24f, 26.17f)
            lineTo(31.33f, 26.17f)
            curveTo(32.5f, 26.17f, 33.6f, 25.54f, 34.2f, 24.53f)
            curveTo(34.45f, 24.12f, 34.31f, 23.58f, 33.89f, 23.34f)
            curveTo(33.48f, 23.09f, 32.94f, 23.23f, 32.69f, 23.64f)
            curveTo(32.41f, 24.13f, 31.9f, 24.42f, 31.33f, 24.42f)
            lineTo(23.02f, 24.42f)
            curveTo(22.15f, 24.42f, 21.44f, 23.71f, 21.44f, 22.83f)
            curveTo(21.44f, 21.96f, 22.15f, 21.25f, 23.02f, 21.25f)
            close()
        }
    }.build()
}
