// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ThumbsDown: ImageVector by lazy {
    ImageVector.Builder(
        name = "ThumbsDown",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFDB5E))) {
            moveTo(34.96f, 18.08f)
            curveTo(34.96f, 18.59f, 34.84f, 19.06f, 34.64f, 19.49f)
            curveTo(33.29f, 23.81f, 27.02f, 23.5f, 18.09f, 23.71f)
            curveTo(16.59f, 23.74f, 17.45f, 25.51f, 17.97f, 29.38f)
            curveTo(18.31f, 31.89f, 16.69f, 35.76f, 13.96f, 35.76f)
            curveTo(9.46f, 35.76f, 13.79f, 32.21f, 9.81f, 23.44f)
            curveTo(7.69f, 18.75f, 2.94f, 21.38f, 2.94f, 16.67f)
            lineTo(2.94f, 5.95f)
            curveTo(2.94f, 4.12f, 3.12f, 2.35f, 5.7f, 2.06f)
            curveTo(8.2f, 1.78f, 7.63f, 0f, 11.24f, 0f)
            lineTo(29.28f, 0f)
            curveTo(31.12f, 0f, 32.62f, 1.5f, 32.62f, 3.33f)
            curveTo(32.62f, 4.1f, 32.35f, 4.79f, 31.92f, 5.35f)
            curveTo(32.94f, 5.92f, 33.64f, 7f, 33.64f, 8.25f)
            curveTo(33.64f, 9.01f, 33.37f, 9.71f, 32.94f, 10.27f)
            curveTo(33.96f, 10.84f, 34.67f, 11.92f, 34.67f, 13.17f)
            curveTo(34.67f, 14.08f, 34.3f, 14.9f, 33.71f, 15.5f)
            curveTo(34.46f, 16.11f, 34.96f, 17.04f, 34.96f, 18.08f)
            close()
        }
        path(fill = SolidColor(Color(0xFFEE9547))) {
            moveTo(23.02f, 14.75f)
            lineTo(31.62f, 14.75f)
            curveTo(32.79f, 14.75f, 33.89f, 15.38f, 34.49f, 16.38f)
            curveTo(34.74f, 16.8f, 34.6f, 17.34f, 34.18f, 17.58f)
            curveTo(33.77f, 17.83f, 33.23f, 17.69f, 32.98f, 17.28f)
            curveTo(32.7f, 16.8f, 32.18f, 16.5f, 31.62f, 16.5f)
            lineTo(22.81f, 16.5f)
            curveTo(21.94f, 16.5f, 21.23f, 17.21f, 21.23f, 18.08f)
            curveTo(21.23f, 18.96f, 21.94f, 19.67f, 22.81f, 19.67f)
            lineTo(28.7f, 19.67f)
            curveTo(29.18f, 19.67f, 29.57f, 20.06f, 29.57f, 20.54f)
            curveTo(29.57f, 21.03f, 29.18f, 21.42f, 28.7f, 21.42f)
            lineTo(22.81f, 21.42f)
            curveTo(20.97f, 21.42f, 19.48f, 19.92f, 19.48f, 18.08f)
            curveTo(19.48f, 17.06f, 19.95f, 16.15f, 20.68f, 15.54f)
            curveTo(20.07f, 14.94f, 19.69f, 14.1f, 19.69f, 13.17f)
            curveTo(19.69f, 12.14f, 20.16f, 11.23f, 20.9f, 10.62f)
            curveTo(20.29f, 10.01f, 19.91f, 9.18f, 19.91f, 8.25f)
            curveTo(19.91f, 7.13f, 20.47f, 6.14f, 21.32f, 5.54f)
            curveTo(20.79f, 4.95f, 20.46f, 4.18f, 20.46f, 3.33f)
            curveTo(20.46f, 1.5f, 21.96f, 0f, 23.8f, 0f)
            lineTo(29.28f, 0f)
            curveTo(30.45f, 0f, 31.55f, 0.63f, 32.15f, 1.63f)
            curveTo(32.4f, 2.05f, 32.26f, 2.59f, 31.84f, 2.83f)
            curveTo(31.43f, 3.08f, 30.89f, 2.94f, 30.64f, 2.53f)
            curveTo(30.36f, 2.05f, 29.84f, 1.75f, 29.28f, 1.75f)
            lineTo(23.8f, 1.75f)
            curveTo(22.92f, 1.75f, 22.21f, 2.46f, 22.21f, 3.33f)
            curveTo(22.21f, 4.21f, 22.92f, 4.92f, 23.8f, 4.92f)
            lineTo(30.3f, 4.92f)
            curveTo(31.47f, 4.92f, 32.57f, 5.54f, 33.17f, 6.55f)
            curveTo(33.42f, 6.97f, 33.28f, 7.5f, 32.87f, 7.75f)
            curveTo(32.45f, 8f, 31.91f, 7.86f, 31.67f, 7.44f)
            curveTo(31.38f, 6.96f, 30.87f, 6.67f, 30.3f, 6.67f)
            lineTo(23.24f, 6.67f)
            curveTo(22.37f, 6.67f, 21.66f, 7.38f, 21.66f, 8.25f)
            curveTo(21.66f, 9.12f, 22.37f, 9.83f, 23.24f, 9.83f)
            lineTo(31.33f, 9.83f)
            curveTo(32.5f, 9.83f, 33.6f, 10.46f, 34.2f, 11.47f)
            curveTo(34.45f, 11.88f, 34.31f, 12.42f, 33.89f, 12.67f)
            curveTo(33.48f, 12.91f, 32.94f, 12.78f, 32.69f, 12.36f)
            curveTo(32.41f, 11.87f, 31.9f, 11.58f, 31.33f, 11.58f)
            lineTo(23.02f, 11.58f)
            curveTo(22.15f, 11.58f, 21.44f, 12.29f, 21.44f, 13.17f)
            curveTo(21.44f, 14.04f, 22.15f, 14.75f, 23.02f, 14.75f)
            close()
        }
    }.build()
}
