// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.shadcncompose.icons.emoji

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Warning: ImageVector by lazy {
    ImageVector.Builder(
        name = "Warning",
        defaultWidth = 36f.dp,
        defaultHeight = 36f.dp,
        viewportWidth = 36f,
        viewportHeight = 36f,
    ).apply {
        path(fill = SolidColor(Color(0xFFFFCC4D))) {
            moveTo(2.65f, 35f)
            curveTo(0.81f, 35f, -0f, 33.66f, 0.85f, 32.03f)
            lineTo(16.46f, 1.97f)
            curveTo(17.3f, 0.34f, 18.69f, 0.34f, 19.54f, 1.97f)
            lineTo(35.15f, 32.03f)
            curveTo(36f, 33.66f, 35.19f, 35f, 33.35f, 35f)
            lineTo(2.65f, 35f)
            close()
        }
        path(fill = SolidColor(Color(0xFF231F20))) {
            moveTo(15.58f, 28.95f)
            curveTo(15.58f, 27.62f, 16.67f, 26.54f, 18f, 26.54f)
            curveTo(19.33f, 26.54f, 20.42f, 27.62f, 20.42f, 28.95f)
            curveTo(20.42f, 30.29f, 19.33f, 31.37f, 18f, 31.37f)
            curveTo(16.67f, 31.37f, 15.58f, 30.29f, 15.58f, 28.95f)
            close()
            moveTo(15.77f, 10.66f)
            curveTo(15.77f, 9.36f, 16.73f, 8.55f, 18f, 8.55f)
            curveTo(19.24f, 8.55f, 20.23f, 9.39f, 20.23f, 10.66f)
            lineTo(20.23f, 22.6f)
            curveTo(20.23f, 23.87f, 19.24f, 24.71f, 18f, 24.71f)
            curveTo(16.73f, 24.71f, 15.77f, 23.9f, 15.77f, 22.6f)
            lineTo(15.77f, 10.66f)
            close()
        }
    }.build()
}
