#!/usr/bin/env python3
"""
KMM ImageVector Generator — raster/SVG → compiled Kotlin ImageVector.

Pipeline:
  PNG/JPG ─► ①quantize (Pillow) ─► ②trace (vtracer|potrace) ─► SVG ─┐
  SVG ────────────────────────────────────────────────────────────┴─► ③normalize ─► ④Kotlin

The core (③④) is pure Python with zero dependencies: an SVG path parser that emits
absolute coordinates rescaled to a canonical viewport, piped into an ImageVector.Builder
template. Raster ingestion (①②) is an optional front-end that degrades gracefully with
install hints when Pillow/vtracer/potrace are missing.

Agents must NEVER hand-write ImageVector path coordinates — they run this script and wire
the generated `AppIcons.<Name>` reference. Generated files carry a header marker that the
architecture audit checks; hand-written builders without it are flagged.

Usage:
  # From an SVG (no dependencies needed)
  python3 convert_image_to_imagevector.py logo.svg --name Logo --group-id com.example.app

  # From a raster (requires Pillow + vtracer or potrace)
  python3 convert_image_to_imagevector.py logo.png --name Logo --colors 4

  # Icon tinted at the call site (single color-agnostic layer)
  python3 convert_image_to_imagevector.py icon.svg --name Search --color-mode semantic
"""
from __future__ import annotations

import argparse
import math
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

GENERATED_HEADER = "// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead."

DEFAULT_VIEWPORT = 24.0
DEFAULT_MAX_NODES = 400


# ── ③ SVG path parsing (pure Python, no deps) ─────────────────────────────────

_NUM_RE = re.compile(r"[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?")
_CMD_RE = re.compile(r"([MmLlHhVvCcSsQqTtZzAa])([^MmLlHhVvCcSsQqTtZzAa]*)")


class PathCommand:
    """One absolute-coordinate drawing command: op in {move,line,curve,quad,close}."""

    def __init__(self, op: str, args: list[float]):
        self.op = op
        self.args = args


def _floats(chunk: str) -> list[float]:
    return [float(m.group(0)) for m in _NUM_RE.finditer(chunk)]


def parse_path(d: str) -> list[PathCommand]:
    """Parse an SVG `d` string into absolute PathCommands.

    Supports M/m L/l H/h V/v C/c S/s Q/q T/t Z/z. Arcs (A/a) are rejected — tracers
    (vtracer, potrace) emit only lines and cubics; arcs from hand-authored SVGs must be
    flattened by the authoring tool first.
    """
    cmds: list[PathCommand] = []
    cx = cy = 0.0          # current point
    sx = sy = 0.0          # subpath start
    pcx = pcy = None       # previous cubic control (for S)
    pqx = pqy = None       # previous quad control (for T)

    for op, chunk in _CMD_RE.findall(d):
        nums = _floats(chunk)
        rel = op.islower()
        u = op.upper()

        if u == "A":
            raise ValueError(
                "arc command (A) not supported — flatten arcs to curves in the authoring "
                "tool, or re-trace the raster (tracers emit cubics only)"
            )

        if u == "Z":
            cmds.append(PathCommand("close", []))
            cx, cy = sx, sy
            pcx = pcy = pqx = pqy = None
            continue

        i = 0
        first = True
        while i < len(nums):
            if u == "M":
                need = 2
                x, y = nums[i], nums[i + 1]
                if rel:
                    x, y = cx + x, cy + y
                if first:
                    cmds.append(PathCommand("move", [x, y]))
                    sx, sy = x, y
                else:
                    cmds.append(PathCommand("line", [x, y]))  # implicit lineto
                cx, cy = x, y
            elif u == "L":
                need = 2
                x, y = nums[i], nums[i + 1]
                if rel:
                    x, y = cx + x, cy + y
                cmds.append(PathCommand("line", [x, y]))
                cx, cy = x, y
            elif u == "H":
                need = 1
                x = nums[i] + (cx if rel else 0.0)
                cmds.append(PathCommand("line", [x, cy]))
                cx = x
            elif u == "V":
                need = 1
                y = nums[i] + (cy if rel else 0.0)
                cmds.append(PathCommand("line", [cx, y]))
                cy = y
            elif u == "C":
                need = 6
                x1, y1, x2, y2, x, y = nums[i:i + 6]
                if rel:
                    x1, y1, x2, y2, x, y = cx + x1, cy + y1, cx + x2, cy + y2, cx + x, cy + y
                cmds.append(PathCommand("curve", [x1, y1, x2, y2, x, y]))
                pcx, pcy = x2, y2
                cx, cy = x, y
            elif u == "S":
                need = 4
                x2, y2, x, y = nums[i:i + 4]
                if rel:
                    x2, y2, x, y = cx + x2, cy + y2, cx + x, cy + y
                # Reflect previous cubic control around current point
                x1 = 2 * cx - pcx if pcx is not None else cx
                y1 = 2 * cy - pcy if pcy is not None else cy
                cmds.append(PathCommand("curve", [x1, y1, x2, y2, x, y]))
                pcx, pcy = x2, y2
                cx, cy = x, y
            elif u == "Q":
                need = 4
                x1, y1, x, y = nums[i:i + 4]
                if rel:
                    x1, y1, x, y = cx + x1, cy + y1, cx + x, cy + y
                cmds.append(PathCommand("quad", [x1, y1, x, y]))
                pqx, pqy = x1, y1
                cx, cy = x, y
            elif u == "T":
                need = 2
                x, y = nums[i:i + 2]
                if rel:
                    x, y = cx + x, cy + y
                x1 = 2 * cx - pqx if pqx is not None else cx
                y1 = 2 * cy - pqy if pqy is not None else cy
                cmds.append(PathCommand("quad", [x1, y1, x, y]))
                pqx, pqy = x1, y1
                cx, cy = x, y
            else:  # pragma: no cover — regex restricts ops
                raise ValueError(f"unsupported path op '{op}'")
            if u not in ("C", "S"):
                pcx = pcy = None
            if u not in ("Q", "T"):
                pqx = pqy = None
            i += need
            first = False
    return cmds


def scale_commands(cmds: list[PathCommand], sx: float, sy: float, tx: float, ty: float) -> list[PathCommand]:
    out = []
    for c in cmds:
        if c.op == "close":
            out.append(c)
            continue
        args = []
        for j in range(0, len(c.args), 2):
            args.append(c.args[j] * sx + tx)
            args.append(c.args[j + 1] * sy + ty)
        out.append(PathCommand(c.op, args))
    return out


# ── SVG document extraction (regex — tracer output is machine-regular) ────────

_SVG_PATH_TAG_RE = re.compile(r"<path\b[^>]*>", re.IGNORECASE | re.DOTALL)
_ATTR_D_RE = re.compile(r'\bd\s*=\s*"([^"]+)"')
_ATTR_FILL_RE = re.compile(r'\bfill\s*=\s*"([^"]+)"')
_VIEWBOX_RE = re.compile(r'\bviewBox\s*=\s*"([\d\s.eE+-]+)"')
_WH_RE = re.compile(r'\bwidth\s*=\s*"([\d.]+)(?:px)?"[^>]*\bheight\s*=\s*"([\d.]+)(?:px)?"', re.DOTALL)


def extract_svg(svg_text: str) -> tuple[list[tuple[str, str]], float, float]:
    """Return ([(d, fill_hex)], source_width, source_height)."""
    vb = _VIEWBOX_RE.search(svg_text)
    if vb:
        parts = [float(p) for p in vb.group(1).split()]
        w, h = parts[2], parts[3]
    else:
        wh = _WH_RE.search(svg_text)
        if not wh:
            raise ValueError("SVG has neither viewBox nor width/height — cannot determine viewport")
        w, h = float(wh.group(1)), float(wh.group(2))

    paths: list[tuple[str, str]] = []
    for tag in _SVG_PATH_TAG_RE.findall(svg_text):
        d = _ATTR_D_RE.search(tag)
        if not d:
            continue
        fill_m = _ATTR_FILL_RE.search(tag)
        fill = fill_m.group(1) if fill_m else "#000000"
        if fill.lower() == "none":
            continue
        paths.append((d.group(1), fill))
    return paths, w, h


def _fill_to_argb(fill: str) -> str:
    f = fill.strip().lstrip("#")
    if re.fullmatch(r"[0-9a-fA-F]{3}", f):
        f = "".join(ch * 2 for ch in f)
    if re.fullmatch(r"[0-9a-fA-F]{6}", f):
        return f"0xFF{f.upper()}"
    if re.fullmatch(r"[0-9a-fA-F]{8}", f):
        return f"0x{f.upper()}"
    # rgb(...) form from some tracers
    m = re.fullmatch(r"rgb\((\d+),\s*(\d+),\s*(\d+)\)", fill.strip(), re.IGNORECASE)
    if m:
        return "0xFF" + "".join(f"{int(v):02X}" for v in m.groups())
    return "0xFF000000"


# ── ④ Kotlin codegen ──────────────────────────────────────────────────────────

def _fmt(v: float) -> str:
    return f"{round(v, 2):g}f"


def _cmd_to_kotlin(c: PathCommand) -> str:
    a = c.args
    if c.op == "move":
        return f"moveTo({_fmt(a[0])}, {_fmt(a[1])})"
    if c.op == "line":
        return f"lineTo({_fmt(a[0])}, {_fmt(a[1])})"
    if c.op == "curve":
        return (f"curveTo({_fmt(a[0])}, {_fmt(a[1])}, {_fmt(a[2])}, "
                f"{_fmt(a[3])}, {_fmt(a[4])}, {_fmt(a[5])})")
    if c.op == "quad":
        return f"quadTo({_fmt(a[0])}, {_fmt(a[1])}, {_fmt(a[2])}, {_fmt(a[3])})"
    return "close()"


def generate_kotlin(
    name: str,
    layers: list[tuple[list[PathCommand], str]],
    group_id: str,
    viewport: float,
    color_mode: str,
) -> str:
    pkg = f"{group_id}.core.designsystem.icons"
    body_blocks = []
    for cmds, argb in layers:
        if color_mode == "semantic":
            fill = "SolidColor(Color.Black)  // color-agnostic — tint at the call site"
        else:
            fill = f"SolidColor(Color({argb}))"
        lines = "\n".join(f"                {_cmd_to_kotlin(c)}" for c in cmds)
        body_blocks.append(
            f"            path(fill = {fill}) {{\n{lines}\n            }}"
        )
    paths_kt = "\n".join(body_blocks)
    vp = f"{viewport:g}f"
    return f"""\
{GENERATED_HEADER}
package {pkg}

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val {name}: ImageVector by lazy {{
    ImageVector.Builder(
        name = "{name}",
        defaultWidth = {vp}.dp,
        defaultHeight = {vp}.dp,
        viewportWidth = {vp},
        viewportHeight = {vp},
    ).apply {{
{paths_kt}
    }}.build()
}}
"""


# ── ①② Raster front-end (optional deps, graceful degrade) ─────────────────────

def trace_raster_to_svg(image_path: Path, colors: int) -> str:
    """Trace a raster into SVG text using vtracer (preferred) or potrace (fallback)."""
    try:
        import vtracer  # type: ignore
    except ImportError:
        vtracer = None

    if vtracer is not None:
        with tempfile.NamedTemporaryFile(suffix=".svg", delete=False) as tmp:
            out_path = Path(tmp.name)
        vtracer.convert_image_to_svg_py(
            str(image_path), str(out_path),
            colormode="color", color_precision=max(1, min(8, colors)),
            mode="spline", filter_speckle=4,
        )
        return out_path.read_text(encoding="utf-8")

    potrace_bin = shutil.which("potrace")
    if potrace_bin:
        try:
            from PIL import Image  # type: ignore
        except ImportError:
            raise SystemExit(
                "raster input needs Pillow for the potrace fallback: pip install Pillow"
            )
        # Monochrome fallback: threshold to a PBM, trace to SVG
        with tempfile.TemporaryDirectory() as td:
            pbm = Path(td) / "in.pbm"
            svg = Path(td) / "out.svg"
            img = Image.open(image_path).convert("L").point(lambda p: 0 if p < 160 else 255, "1")
            img.save(pbm)
            subprocess.run([potrace_bin, str(pbm), "-s", "-o", str(svg)], check=True)
            return svg.read_text(encoding="utf-8")

    raise SystemExit(
        "no tracer available for raster input.\n"
        "  Install one of:\n"
        "    pip install vtracer      (preferred — full color)\n"
        "    brew install potrace     (fallback — monochrome)\n"
        "  Or convert the image to SVG externally and pass the .svg here."
    )


def entropy_gate(image_path: Path) -> None:
    """Reject photographs — this tool is for logos/icons/flat art only."""
    try:
        from PIL import Image  # type: ignore
    except ImportError:
        return  # can't check without Pillow; vtracer path may still work
    img = Image.open(image_path).convert("RGB").resize((64, 64))
    unique = len(set(img.getdata()))
    if unique > 2600:  # >~64% unique colors in a 64x64 thumb → photographic content
        raise SystemExit(
            f"input looks photographic ({unique} unique colors in a 64x64 sample) — "
            "tracing photos produces garbage vectors. This tool is for logos, icons, "
            "and flat illustrations. Keep photos as raster under assets/photos/."
        )


# ── main ──────────────────────────────────────────────────────────────────────

def pascal(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p) or "Icon"


def convert(
    source: Path,
    name: str,
    group_id: str,
    viewport: float,
    color_mode: str,
    colors: int,
    max_nodes: int,
) -> tuple[str, dict]:
    """Full conversion. Returns (kotlin_source, report)."""
    if source.suffix.lower() == ".svg":
        svg_text = source.read_text(encoding="utf-8")
    else:
        entropy_gate(source)
        svg_text = trace_raster_to_svg(source, colors)

    raw_paths, src_w, src_h = extract_svg(svg_text)
    if not raw_paths:
        raise ValueError("no fillable <path> elements found in the SVG")

    # Uniform scale into the canonical viewport, centered
    scale = viewport / max(src_w, src_h)
    tx = (viewport - src_w * scale) / 2
    ty = (viewport - src_h * scale) / 2

    layers: list[tuple[list[PathCommand], str]] = []
    total_nodes = 0
    for d, fill in raw_paths:
        cmds = scale_commands(parse_path(d), scale, scale, tx, ty)
        total_nodes += len(cmds)
        layers.append((cmds, _fill_to_argb(fill)))

    if total_nodes > max_nodes:
        raise SystemExit(
            f"traced output has {total_nodes} path nodes (budget {max_nodes}) — the vector "
            f"would bloat the binary and recomposition. Re-run with fewer --colors, simplify "
            f"the source art, or raise --max-nodes deliberately."
        )

    if color_mode == "semantic" and len(layers) > 1:
        # Semantic icons must be single-layer (tinted at call site); merge all layers.
        merged: list[PathCommand] = []
        for cmds, _ in layers:
            merged.extend(cmds)
        layers = [(merged, "0xFF000000")]

    kotlin = generate_kotlin(name, layers, group_id, viewport, color_mode)
    report = {
        "name": name,
        "layers": len(layers),
        "nodes": total_nodes,
        "viewport": viewport,
        "color_mode": color_mode,
        "source": str(source),
    }
    return kotlin, report


def main() -> int:
    p = argparse.ArgumentParser(description="Compile a raster/SVG into a Kotlin ImageVector.")
    p.add_argument("input", type=Path, help="Source image (.svg, .png, .jpg, .jpeg, .webp)")
    p.add_argument("--name", help="Kotlin property name (PascalCase; default: from filename)")
    p.add_argument("--group-id", default="com.example.app", help="Package prefix")
    p.add_argument("--output", type=Path, help="Output dir (default: core/designsystem/icons/ under CWD)")
    p.add_argument("--viewport", type=float, default=DEFAULT_VIEWPORT,
                   help=f"Canonical square viewport (default {DEFAULT_VIEWPORT:g} for icons)")
    p.add_argument("--color-mode", choices=("semantic", "literal"), default="literal",
                   help="semantic = single color-agnostic layer tinted at call site; literal = baked colors")
    p.add_argument("--colors", type=int, default=6, help="Quantization colors for raster tracing")
    p.add_argument("--max-nodes", type=int, default=DEFAULT_MAX_NODES, help="Path node budget")
    args = p.parse_args()

    if not args.input.exists():
        print(f"error: {args.input} not found", file=sys.stderr)
        return 2

    name = pascal(args.name or args.input.stem)
    kotlin, report = convert(
        args.input, name, args.group_id, args.viewport,
        args.color_mode, args.colors, args.max_nodes,
    )

    out_dir = args.output or Path("core/designsystem/icons")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{name}.kt"
    out_file.write_text(kotlin, encoding="utf-8")

    print(f"✅  {out_file}")
    print(f"    layers: {report['layers']}  nodes: {report['nodes']}  "
          f"viewport: {report['viewport']:g}  color-mode: {report['color_mode']}")
    print(f"    Wire it up: Icon(imageVector = {name}, contentDescription = …"
          + (", tint = AppTheme.colors.onSurface)" if args.color_mode == "semantic" else ")"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
