#!/usr/bin/env python3
"""
KMP ImageVector Generator — raster/SVG → compiled Kotlin ImageVector.

Pipeline:
  PNG/JPG ─► ①quantize (Pillow) ─► ②trace (vtracer|potrace) ─► SVG ─┐
  SVG ────────────────────────────────────────────────────────────┴─► ③normalize ─► ④Kotlin

The core (③④) is pure Python with zero dependencies: an SVG path parser that emits
absolute coordinates rescaled to a canonical viewport, piped into an ImageVector.Builder
template. Raster ingestion (①②) is an optional front-end that degrades gracefully with
install hints when Pillow/vtracer/potrace are missing.

Agents must NEVER hand-write ImageVector path coordinates — they run this script and wire
the generated `AppIcons.<Name>` reference. Generated files carry a header marker that the
architecture audit checks; hand-written builders without it are flagged.

Usage:
  # From an SVG (no dependencies needed)
  python3 convert_image_to_imagevector.py logo.svg --name Logo --group-id com.example.app

  # From a raster (requires Pillow + vtracer or potrace)
  python3 convert_image_to_imagevector.py logo.png --name Logo --colors 4

  # Icon tinted at the call site (single color-agnostic layer)
  python3 convert_image_to_imagevector.py icon.svg --name Search --color-mode semantic
"""
from __future__ import annotations

import argparse
import math
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

GENERATED_HEADER = "// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead."

DEFAULT_VIEWPORT = 24.0
DEFAULT_MAX_NODES = 400


# ── ③ SVG path parsing (pure Python, no deps) ─────────────────────────────────

_NUM_RE = re.compile(r"[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?")
_CMD_RE = re.compile(r"([MmLlHhVvCcSsQqTtZzAa])([^MmLlHhVvCcSsQqTtZzAa]*)")


class PathCommand:
    """One absolute-coordinate drawing command: op in {move,line,curve,quad,close}."""

    def __init__(self, op: str, args: list[float]):
        self.op = op
        self.args = args


def _floats(chunk: str) -> list[float]:
    return [float(m.group(0)) for m in _NUM_RE.finditer(chunk)]


def _parse_arc_args(chunk: str) -> list[list[float]]:
    """Parse the argument chunk of an SVG A/a command into groups of 7 floats
    (rx, ry, x-axis-rotation, large-arc-flag, sweep-flag, x, y).

    The two flags are always a single 0/1 digit and the SVG grammar allows them to be
    packed with NO separator before the next token (e.g. "1112" means flag=1, flag=1,
    x=12) — a well-known gotcha that a generic float-tokenizing regex gets wrong by
    reading "1112" as one number. Flags are read one character at a time instead.
    """
    i = 0
    n = len(chunk)
    groups: list[list[float]] = []

    def skip_sep() -> None:
        nonlocal i
        while i < n and chunk[i] in " ,\t\r\n":
            i += 1

    def read_number() -> float:
        nonlocal i
        skip_sep()
        m = _NUM_RE.match(chunk, i)
        if not m:
            raise ValueError(f"malformed arc argument at position {i}: {chunk!r}")
        i = m.end()
        return float(m.group(0))

    def read_flag() -> float:
        nonlocal i
        skip_sep()
        if i >= n or chunk[i] not in "01":
            raise ValueError(f"malformed arc flag at position {i}: {chunk!r}")
        val = float(chunk[i])
        i += 1
        return val

    while True:
        skip_sep()
        if i >= n:
            break
        rx = read_number()
        ry = read_number()
        rot = read_number()
        large_arc = read_flag()
        sweep = read_flag()
        x = read_number()
        y = read_number()
        groups.append([rx, ry, rot, large_arc, sweep, x, y])
    return groups


_ArcSegment = tuple[
    Optional[tuple[float, float]],  # control point 1, or None for a straight-line segment
    Optional[tuple[float, float]],  # control point 2, or None for a straight-line segment
    tuple[float, float],            # segment end point (always present)
]


def _arc_to_cubics(
    x1: float, y1: float,
    rx: float, ry: float, phi_deg: float,
    large_arc: bool, sweep: bool,
    x2: float, y2: float,
) -> list[_ArcSegment]:
    """Convert one SVG elliptical arc segment to a list of cubic Bezier curves.

    Standard endpoint-to-center parameterization (SVG 1.1 spec Appendix F.6.5), then
    each arc is split into sub-segments of at most 90 degrees and each sub-segment is
    approximated with a cubic Bezier using the standard kappa = 4/3*tan(delta/4)
    construction — the same technique used by picosvg/FontTools/Blink's arc-to-cubic
    converters. Returns (control1, control2, end) tuples; control1/control2 are `None`
    for a degenerate zero-radius arc, signaling the caller to emit a cheaper `lineTo`
    instead of a `curveTo` whose control points would just sit on the straight line.
    """
    if x1 == x2 and y1 == y2:
        return []  # zero-length arc — nothing to draw
    if rx == 0 or ry == 0:
        return [(None, None, (x2, y2))]  # degenerate ellipse — a straight line, not a curve

    rx, ry = abs(rx), abs(ry)
    phi = math.radians(phi_deg % 360)
    cos_phi, sin_phi = math.cos(phi), math.sin(phi)

    # F.6.5.1 — compute (x1', y1'), the current point in the rotated ellipse frame
    dx2, dy2 = (x1 - x2) / 2.0, (y1 - y2) / 2.0
    x1p = cos_phi * dx2 + sin_phi * dy2
    y1p = -sin_phi * dx2 + cos_phi * dy2

    # F.6.6.1 — correct out-of-range radii
    lam = (x1p ** 2) / (rx ** 2) + (y1p ** 2) / (ry ** 2)
    if lam > 1:
        s = math.sqrt(lam)
        rx *= s
        ry *= s

    # F.6.5.2 — compute (cx', cy')
    rx_sq, ry_sq = rx * rx, ry * ry
    x1p_sq, y1p_sq = x1p * x1p, y1p * y1p
    num = rx_sq * ry_sq - rx_sq * y1p_sq - ry_sq * x1p_sq
    den = rx_sq * y1p_sq + ry_sq * x1p_sq
    co = math.sqrt(max(num / den, 0.0)) if den != 0 else 0.0
    if large_arc == sweep:
        co = -co
    cxp = co * (rx * y1p / ry)
    cyp = co * (-ry * x1p / rx)

    # F.6.5.3 — compute (cx, cy) in the original frame
    cx = cos_phi * cxp - sin_phi * cyp + (x1 + x2) / 2.0
    cy = sin_phi * cxp + cos_phi * cyp + (y1 + y2) / 2.0

    def _angle(ux: float, uy: float, vx: float, vy: float) -> float:
        dot = ux * vx + uy * vy
        length = math.sqrt((ux * ux + uy * uy) * (vx * vx + vy * vy))
        ang = math.acos(max(-1.0, min(1.0, dot / length))) if length != 0 else 0.0
        return -ang if (ux * vy - uy * vx) < 0 else ang

    # F.6.5.4 / F.6.5.5 — start angle theta1 and sweep angle delta-theta
    theta1 = _angle(1.0, 0.0, (x1p - cxp) / rx, (y1p - cyp) / ry)
    dtheta = _angle((x1p - cxp) / rx, (y1p - cyp) / ry, (-x1p - cxp) / rx, (-y1p - cyp) / ry)
    if not sweep and dtheta > 0:
        dtheta -= 2 * math.pi
    elif sweep and dtheta < 0:
        dtheta += 2 * math.pi

    # Split into <=90-degree sub-segments so the cubic approximation stays accurate.
    # The +0.001 epsilon (matching picosvg/FontTools/Blink's reference implementation)
    # absorbs floating-point trig roundoff on exact 90-degree-multiple arcs — without
    # it, a dtheta that should be exactly pi/2 can come out as e.g. 1.5707963267948968
    # and `ceil()` rounds up to one extra, unnecessary segment.
    num_segments = max(1, math.ceil(abs(dtheta) / (math.pi / 2 + 0.001)))
    delta = dtheta / num_segments
    kappa = 4.0 / 3.0 * math.tan(delta / 4.0)

    def to_ellipse(px: float, py: float) -> tuple[float, float]:
        ex = cx + rx * cos_phi * px - ry * sin_phi * py
        ey = cy + rx * sin_phi * px + ry * cos_phi * py
        return ex, ey

    segments: list[_ArcSegment] = []
    theta = theta1
    for _ in range(num_segments):
        theta_next = theta + delta
        cos_t, sin_t = math.cos(theta), math.sin(theta)
        cos_tn, sin_tn = math.cos(theta_next), math.sin(theta_next)

        c1 = to_ellipse(cos_t - kappa * sin_t, sin_t + kappa * cos_t)
        c2 = to_ellipse(cos_tn + kappa * sin_tn, sin_tn - kappa * cos_tn)
        end = to_ellipse(cos_tn, sin_tn)
        segments.append((c1, c2, end))
        theta = theta_next

    return segments


def parse_path(d: str) -> list[PathCommand]:
    """Parse an SVG `d` string into absolute PathCommands.

    Supports M/m L/l H/h V/v C/c S/s Q/q T/t Z/z A/a. Arcs (A/a) are flattened into
    cubic Beziers via `_arc_to_cubics` (the standard SVG spec endpoint-to-center
    parameterization) so they can be emitted as `curveTo(...)` alongside every other
    command — ImageVector.Builder has no native arc primitive, same as the tracers'
    own output, so arcs and cubics both end up on the same code path.
    """
    cmds: list[PathCommand] = []
    cx = cy = 0.0          # current point
    sx = sy = 0.0          # subpath start
    pcx = pcy = None       # previous cubic control (for S)
    pqx = pqy = None       # previous quad control (for T)

    for op, chunk in _CMD_RE.findall(d):
        rel = op.islower()
        u = op.upper()

        if u == "A":
            for rx, ry, rot, large_arc, sweep, ex, ey in _parse_arc_args(chunk):
                x2, y2 = (cx + ex, cy + ey) if rel else (ex, ey)
                for c1, c2, end in _arc_to_cubics(
                    cx, cy, rx, ry, rot, bool(large_arc), bool(sweep), x2, y2
                ):
                    if c1 is None:
                        # Degenerate zero-radius arc — a straight line, cheaper than a
                        # curveTo whose control points would just sit on that line.
                        cmds.append(PathCommand("line", [end[0], end[1]]))
                    else:
                        cmds.append(PathCommand("curve", [c1[0], c1[1], c2[0], c2[1], end[0], end[1]]))
                    cx, cy = end
            pcx = pcy = pqx = pqy = None
            continue

        nums = _floats(chunk)

        if u == "Z":
            cmds.append(PathCommand("close", []))
            cx, cy = sx, sy
            pcx = pcy = pqx = pqy = None
            continue

        i = 0
        first = True
        while i < len(nums):
            if u == "M":
                need = 2
                x, y = nums[i], nums[i + 1]
                if rel:
                    x, y = cx + x, cy + y
                if first:
                    cmds.append(PathCommand("move", [x, y]))
                    sx, sy = x, y
                else:
                    cmds.append(PathCommand("line", [x, y]))  # implicit lineto
                cx, cy = x, y
            elif u == "L":
                need = 2
                x, y = nums[i], nums[i + 1]
                if rel:
                    x, y = cx + x, cy + y
                cmds.append(PathCommand("line", [x, y]))
                cx, cy = x, y
            elif u == "H":
                need = 1
                x = nums[i] + (cx if rel else 0.0)
                cmds.append(PathCommand("line", [x, cy]))
                cx = x
            elif u == "V":
                need = 1
                y = nums[i] + (cy if rel else 0.0)
                cmds.append(PathCommand("line", [cx, y]))
                cy = y
            elif u == "C":
                need = 6
                x1, y1, x2, y2, x, y = nums[i:i + 6]
                if rel:
                    x1, y1, x2, y2, x, y = cx + x1, cy + y1, cx + x2, cy + y2, cx + x, cy + y
                cmds.append(PathCommand("curve", [x1, y1, x2, y2, x, y]))
                pcx, pcy = x2, y2
                cx, cy = x, y
            elif u == "S":
                need = 4
                x2, y2, x, y = nums[i:i + 4]
                if rel:
                    x2, y2, x, y = cx + x2, cy + y2, cx + x, cy + y
                # Reflect previous cubic control around current point
                x1 = 2 * cx - pcx if pcx is not None else cx
                y1 = 2 * cy - pcy if pcy is not None else cy
                cmds.append(PathCommand("curve", [x1, y1, x2, y2, x, y]))
                pcx, pcy = x2, y2
                cx, cy = x, y
            elif u == "Q":
                need = 4
                x1, y1, x, y = nums[i:i + 4]
                if rel:
                    x1, y1, x, y = cx + x1, cy + y1, cx + x, cy + y
                cmds.append(PathCommand("quad", [x1, y1, x, y]))
                pqx, pqy = x1, y1
                cx, cy = x, y
            elif u == "T":
                need = 2
                x, y = nums[i:i + 2]
                if rel:
                    x, y = cx + x, cy + y
                x1 = 2 * cx - pqx if pqx is not None else cx
                y1 = 2 * cy - pqy if pqy is not None else cy
                cmds.append(PathCommand("quad", [x1, y1, x, y]))
                pqx, pqy = x1, y1
                cx, cy = x, y
            else:  # pragma: no cover — regex restricts ops
                raise ValueError(f"unsupported path op '{op}'")
            if u not in ("C", "S"):
                pcx = pcy = None
            if u not in ("Q", "T"):
                pqx = pqy = None
            i += need
            first = False
    return cmds


def scale_commands(cmds: list[PathCommand], sx: float, sy: float, tx: float, ty: float) -> list[PathCommand]:
    out = []
    for c in cmds:
        if c.op == "close":
            out.append(c)
            continue
        args = []
        for j in range(0, len(c.args), 2):
            args.append(c.args[j] * sx + tx)
            args.append(c.args[j + 1] * sy + ty)
        out.append(PathCommand(c.op, args))
    return out


# ── SVG document extraction (regex — tracer output is machine-regular) ────────

_SVG_PATH_TAG_RE = re.compile(r"<path\b[^>]*>", re.IGNORECASE | re.DOTALL)
_ATTR_D_RE = re.compile(r'\bd\s*=\s*"([^"]+)"')
_ATTR_FILL_RE = re.compile(r'\bfill\s*=\s*"([^"]+)"')
_VIEWBOX_RE = re.compile(r'\bviewBox\s*=\s*"([\d\s.eE+-]+)"')
_WH_RE = re.compile(r'\bwidth\s*=\s*"([\d.]+)(?:px)?"[^>]*\bheight\s*=\s*"([\d.]+)(?:px)?"', re.DOTALL)


def extract_svg(svg_text: str) -> tuple[list[tuple[str, str]], float, float]:
    """Return ([(d, fill_hex)], source_width, source_height)."""
    vb = _VIEWBOX_RE.search(svg_text)
    if vb:
        parts = [float(p) for p in vb.group(1).split()]
        w, h = parts[2], parts[3]
    else:
        wh = _WH_RE.search(svg_text)
        if not wh:
            raise ValueError("SVG has neither viewBox nor width/height — cannot determine viewport")
        w, h = float(wh.group(1)), float(wh.group(2))

    paths: list[tuple[str, str]] = []
    for tag in _SVG_PATH_TAG_RE.findall(svg_text):
        d = _ATTR_D_RE.search(tag)
        if not d:
            continue
        fill_m = _ATTR_FILL_RE.search(tag)
        fill = fill_m.group(1) if fill_m else "#000000"
        if fill.lower() == "none":
            continue
        paths.append((d.group(1), fill))
    return paths, w, h


def _fill_to_argb(fill: str) -> str:
    f = fill.strip().lstrip("#")
    if re.fullmatch(r"[0-9a-fA-F]{3}", f):
        f = "".join(ch * 2 for ch in f)
    if re.fullmatch(r"[0-9a-fA-F]{6}", f):
        return f"0xFF{f.upper()}"
    if re.fullmatch(r"[0-9a-fA-F]{8}", f):
        return f"0x{f.upper()}"
    # rgb(...) form from some tracers
    m = re.fullmatch(r"rgb\((\d+),\s*(\d+),\s*(\d+)\)", fill.strip(), re.IGNORECASE)
    if m:
        return "0xFF" + "".join(f"{int(v):02X}" for v in m.groups())
    return "0xFF000000"


# ── ④ Kotlin codegen ──────────────────────────────────────────────────────────

def _fmt(v: float) -> str:
    return f"{round(v, 2):g}f"


def _cmd_to_kotlin(c: PathCommand) -> str:
    a = c.args
    if c.op == "move":
        return f"moveTo({_fmt(a[0])}, {_fmt(a[1])})"
    if c.op == "line":
        return f"lineTo({_fmt(a[0])}, {_fmt(a[1])})"
    if c.op == "curve":
        return (f"curveTo({_fmt(a[0])}, {_fmt(a[1])}, {_fmt(a[2])}, "
                f"{_fmt(a[3])}, {_fmt(a[4])}, {_fmt(a[5])})")
    if c.op == "quad":
        return f"quadTo({_fmt(a[0])}, {_fmt(a[1])}, {_fmt(a[2])}, {_fmt(a[3])})"
    return "close()"


def generate_kotlin(
    name: str,
    layers: list[tuple[list[PathCommand], str]],
    group_id: str,
    viewport: float,
    color_mode: str,
    package: Optional[str] = None,
) -> str:
    # `core.designsystem.icons` is the kmp-compose-design-system skill's own
    # module convention, not a universal one — this script must work standalone for
    # projects that don't use that module layout. `package` overrides it explicitly;
    # the group-id-derived default only applies when the caller doesn't opt in.
    pkg = package or f"{group_id}.core.designsystem.icons"
    body_blocks = []
    for cmds, argb in layers:
        if color_mode == "semantic":
            fill = "SolidColor(Color.Black)"
            fill_comment = "  // color-agnostic — tint at the call site"
        else:
            fill = f"SolidColor(Color({argb}))"
            fill_comment = ""
        lines = "\n".join(f"                {_cmd_to_kotlin(c)}" for c in cmds)
        body_blocks.append(
            f"            path(fill = {fill}) {{{fill_comment}\n{lines}\n            }}"
        )
    paths_kt = "\n".join(body_blocks)
    vp = f"{viewport:g}f"
    return f"""\
{GENERATED_HEADER}
package {pkg}

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val {name}: ImageVector by lazy {{
    ImageVector.Builder(
        name = "{name}",
        defaultWidth = {vp}.dp,
        defaultHeight = {vp}.dp,
        viewportWidth = {vp},
        viewportHeight = {vp},
    ).apply {{
{paths_kt}
    }}.build()
}}
"""


# ── ①② Raster front-end (optional deps, graceful degrade) ─────────────────────

def trace_raster_to_svg(image_path: Path, colors: int) -> str:
    """Trace a raster into SVG text using vtracer (preferred) or potrace (fallback)."""
    try:
        import vtracer  # type: ignore
    except ImportError:
        vtracer = None

    if vtracer is not None:
        with tempfile.NamedTemporaryFile(suffix=".svg", delete=False) as tmp:
            out_path = Path(tmp.name)
        vtracer.convert_image_to_svg_py(
            str(image_path), str(out_path),
            colormode="color", color_precision=max(1, min(8, colors)),
            mode="spline", filter_speckle=4,
        )
        return out_path.read_text(encoding="utf-8")

    potrace_bin = shutil.which("potrace")
    if potrace_bin:
        try:
            from PIL import Image  # type: ignore
        except ImportError:
            raise SystemExit(
                "raster input needs Pillow for the potrace fallback: pip install Pillow"
            )
        # Monochrome fallback: threshold to a PBM, trace to SVG
        with tempfile.TemporaryDirectory() as td:
            pbm = Path(td) / "in.pbm"
            svg = Path(td) / "out.svg"
            img = Image.open(image_path).convert("L").point(lambda p: 0 if p < 160 else 255, "1")
            img.save(pbm)
            subprocess.run([potrace_bin, str(pbm), "-s", "-o", str(svg)], check=True)
            return svg.read_text(encoding="utf-8")

    raise SystemExit(
        "no tracer available for raster input.\n"
        "  Install one of:\n"
        "    pip install vtracer      (preferred — full color)\n"
        "    brew install potrace     (fallback — monochrome)\n"
        "  Or convert the image to SVG externally and pass the .svg here."
    )


def entropy_gate(image_path: Path) -> None:
    """Reject photographs — this tool is for logos/icons/flat art only."""
    try:
        from PIL import Image  # type: ignore
    except ImportError:
        return  # can't check without Pillow; vtracer path may still work
    img = Image.open(image_path).convert("RGB").resize((64, 64))
    unique = len(set(img.getdata()))
    if unique > 2600:  # >~64% unique colors in a 64x64 thumb → photographic content
        raise SystemExit(
            f"input looks photographic ({unique} unique colors in a 64x64 sample) — "
            "tracing photos produces garbage vectors. This tool is for logos, icons, "
            "and flat illustrations. Keep photos as raster under assets/photos/."
        )


# ── Stroke-based SVG normalization (picosvg) ───────────────────────────────────
# This parser only ever reads `fill` — it has no notion of `stroke`/`stroke-width`.
# A stroke-based path's `d` is a CENTERLINE, not an outline; filling it directly
# produces a solid blob instead of the intended outline shape. Worse, this failure is
# silent: it still reports a normal-looking success line (layers/nodes/etc), making a
# badly wrong icon indistinguishable from a correct one. Stroke-only icon sets are
# extremely common (Heroicons Outline, Feather, Lucide, Tabler, Material Symbols
# Outlined — every "outline style" family), so this isn't an edge case to skip; it's
# refused explicitly unless picosvg is available to normalize the stroke into a real
# filled outline path first (via Skia's stroke-to-fill geometry — reimplementing
# correct cap/join/miter handling ourselves would be a serious undertaking).

_STROKE_ATTR_RE = re.compile(r'\bstroke\s*=\s*"([^"]+)"')


def _svg_uses_strokes(svg_text: str) -> bool:
    """True if any `stroke="..."` attribute (on the root `<svg>` or a `<path>`) has a
    real value — not `none`, not empty, not `transparent` — meaning at least one path
    is meant to be drawn as an outlined stroke rather than a filled shape.
    """
    for m in _STROKE_ATTR_RE.finditer(svg_text):
        val = m.group(1).strip().lower()
        if val not in ("none", "", "transparent"):
            return True
    return False


def _normalize_with_picosvg(svg_text: str) -> str:
    """Flatten stroke-to-fill (and, as a side effect, groups/transforms/clip-paths/
    gradients) via picosvg before this script's own flat path parser touches the SVG.
    Raises ValueError with an install hint if picosvg isn't available — never silently
    falls back to filling the centerline.
    """
    try:
        from picosvg.svg import SVG  # type: ignore
    except ImportError:
        raise ValueError(
            "this SVG uses stroke-based paths (fill=\"none\" + stroke=\"...\") — common "
            "in Heroicons Outline, Feather, Lucide, Tabler, and Material Symbols "
            "Outlined. This converter only fills paths directly; it cannot turn a "
            "stroke into a correct outline itself (cap/join/miter geometry). Install "
            "picosvg, which uses Skia to do this correctly, then re-run — no other "
            "changes needed:\n"
            "    pip install picosvg"
        )
    svg = SVG.fromstring(svg_text).topicosvg()
    return svg.tostring()


# ── main ──────────────────────────────────────────────────────────────────────

def pascal(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p) or "Icon"


def convert(
    source: Path,
    name: str,
    group_id: str,
    viewport: float,
    color_mode: str,
    colors: int,
    max_nodes: int,
    package: Optional[str] = None,
) -> tuple[str, dict]:
    """Full conversion. Returns (kotlin_source, report)."""
    if source.suffix.lower() == ".svg":
        svg_text = source.read_text(encoding="utf-8")
        if _svg_uses_strokes(svg_text):
            svg_text = _normalize_with_picosvg(svg_text)
    else:
        entropy_gate(source)
        svg_text = trace_raster_to_svg(source, colors)

    raw_paths, src_w, src_h = extract_svg(svg_text)
    if not raw_paths:
        raise ValueError("no fillable <path> elements found in the SVG")

    # Uniform scale into the canonical viewport, centered
    scale = viewport / max(src_w, src_h)
    tx = (viewport - src_w * scale) / 2
    ty = (viewport - src_h * scale) / 2

    layers: list[tuple[list[PathCommand], str]] = []
    total_nodes = 0
    for d, fill in raw_paths:
        cmds = scale_commands(parse_path(d), scale, scale, tx, ty)
        total_nodes += len(cmds)
        layers.append((cmds, _fill_to_argb(fill)))

    if total_nodes > max_nodes:
        raise SystemExit(
            f"traced output has {total_nodes} path nodes (budget {max_nodes}) — the vector "
            f"would bloat the binary and recomposition. Re-run with fewer --colors, simplify "
            f"the source art, or raise --max-nodes deliberately."
        )

    if color_mode == "semantic" and len(layers) > 1:
        # Semantic icons must be single-layer (tinted at call site); merge all layers.
        merged: list[PathCommand] = []
        for cmds, _ in layers:
            merged.extend(cmds)
        layers = [(merged, "0xFF000000")]

    kotlin = generate_kotlin(name, layers, group_id, viewport, color_mode, package)
    report = {
        "name": name,
        "layers": len(layers),
        "nodes": total_nodes,
        "viewport": viewport,
        "color_mode": color_mode,
        "source": str(source),
    }
    return kotlin, report


def main() -> int:
    p = argparse.ArgumentParser(description="Compile a raster/SVG into a Kotlin ImageVector.")
    p.add_argument("input", type=Path, help="Source image (.svg, .png, .jpg, .jpeg, .webp)")
    p.add_argument("--name", help="Kotlin property name (PascalCase; default: from filename)")
    p.add_argument("--group-id", default="com.example.app", help="Package prefix")
    p.add_argument("--package", help="Full Kotlin package for the generated file "
                   "(default: <group-id>.core.designsystem.icons — the design-system "
                   "skill's module convention. Override this if your project doesn't "
                   "use that module layout.)")
    p.add_argument("--output", type=Path, help="Output dir (default: core/designsystem/icons/ under CWD)")
    p.add_argument("--viewport", type=float, default=DEFAULT_VIEWPORT,
                   help=f"Canonical square viewport (default {DEFAULT_VIEWPORT:g} for icons)")
    p.add_argument("--color-mode", choices=("semantic", "literal"), default="literal",
                   help="semantic = single color-agnostic layer tinted at call site; literal = baked colors")
    p.add_argument("--colors", type=int, default=6, help="Quantization colors for raster tracing")
    p.add_argument("--max-nodes", type=int, default=DEFAULT_MAX_NODES, help="Path node budget")
    args = p.parse_args()

    if not args.input.exists():
        print(f"error: {args.input} not found", file=sys.stderr)
        return 2

    name = pascal(args.name or args.input.stem)
    kotlin, report = convert(
        args.input, name, args.group_id, args.viewport,
        args.color_mode, args.colors, args.max_nodes, args.package,
    )

    out_dir = args.output or Path("core/designsystem/icons")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{name}.kt"
    out_file.write_text(kotlin, encoding="utf-8")

    print(f"✅  {out_file}")
    print(f"    layers: {report['layers']}  nodes: {report['nodes']}  "
          f"viewport: {report['viewport']:g}  color-mode: {report['color_mode']}")
    print(f"    Wire it up: Icon(imageVector = {name}, contentDescription = …"
          + (", tint = AppTheme.colors.onSurface)" if args.color_mode == "semantic" else ")"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
